---
title: "RWorksheet#5_group.Rmd"
author: "Baylon_Calvario_Calzado"
date: "2024-11-20"
output:
  pdf_document:
   latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(polite)
library(kableExtra)
library(rmarkdown)
library(httr)
library(rvest)
library(dplyr)
library(stringr)
library(ggplot2)
```

```{r}
urls <- c('https://www.amazon.com/dp/B09QBVD7BY/ref=sspa_dk_detail_1?psc=1&pd_rd_i=B09QBVD7BY&pd_rd_w=YErdA&content-id=amzn1.sym.8c2f9165-8e93-42a1-8313-73d3809141a2&pf_rd_p=8c2f9165-8e93-42a1-8313-73d3809141a2&pf_rd_r=YGK1ZMXTXRVX69S2S9T0&pd_rd_wg=0Q3Oe&pd_rd_r=a6744fca-8b92-42ea-9265-67523bb4445b&s=wireless&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw', 'https://www.amazon.com/dp/B0D45JFN4T/ref=sspa_dk_detail_4?pd_rd_i=B0D45JFN4T&pd_rd_w=oDGD4&content-id=amzn1.sym.8c2f9165-8e93-42a1-8313-73d3809141a2&pf_rd_p=8c2f9165-8e93-42a1-8313-73d3809141a2&pf_rd_r=YX8BHC2AQF69PHF6Q3TF&pd_rd_wg=bAsOE&pd_rd_r=fc8429c3-aeeb-4478-981c-05ce1854b718&s=wireless&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&th=1', 'https://www.amazon.com/Fossil-Minimalist-Quartz-Stainless-Leather/dp/B079DD13WB/ref=sr_1_6?dib=eyJ2IjoiMSJ9.AFIUHMISy7v70cr9d3Uv3W7CmeBqIZ0bFcWM8jT7D1vdc1s0BuCDkQeIO2-fftK-0RTAjp11Cfs1Foy-NVgHVZx85Yeq4LqSL4KWqF8zlF3hjvqiKkrVI9yrQeKslO-NszyYSTKHrI9weEvmvEiRqTLJYkRe8Np_1wYb57Nea2zQpwjgMcK1P2rGDMx9J8sd5tD210nuDVe0q9Fc6UENeBMqHQSKVnD6H2c0EbYnMewC-kfq0U6g5ZjKsV-aX4tdzdppgn2cEe3dcMPusHLQbcUuENXSHxjw83_D3rvtV30.tw1zhG32m4HA4c6MvGhwJoeARtGe4KvcPOTxUVX7QB8&dib_tag=se&keywords=watch&qid=1733455501&sr=8-6&th=1', 'https://www.amazon.com/Fossil-Quartz-Stainless-Leather-Chronograph/dp/B017SN1OI8/ref=sr_1_8?dib=eyJ2IjoiMSJ9.AFIUHMISy7v70cr9d3Uv3W7CmeBqIZ0bFcWM8jT7D1vdc1s0BuCDkQeIO2-fftK-0RTAjp11Cfs1Foy-NVgHVZx85Yeq4LqSL4KWqF8zlF3hjvqiKkrVI9yrQeKslO-NszyYSTKHrI9weEvmvEiRqTLJYkRe8Np_1wYb57Nea2zQpwjgMcK1P2rGDMx9J8sd5tD210nuDVe0q9Fc6UENeBMqHQSKVnD6H2c0EbYnMewC-kfq0U6g5ZjKsV-aX4tdzdppgn2cEe3dcMPusHLQbcUuENXSHxjw83_D3rvtV30.tw1zhG32m4HA4c6MvGhwJoeARtGe4KvcPOTxUVX7QB8&dib_tag=se&keywords=watch&qid=1733455501&sr=8-8&th=1', 'https://www.amazon.com/Watches-Digital-Stopwatch-Waterproof-Students/dp/B09YT36N1T/ref=sr_1_2_sspa?crid=3PHRTLFXXA920&dib=eyJ2IjoiMSJ9.e97LR5riEFo5QvMDqaXHqvZVy5R67AUP9wSDYidrnwCUXNTmatYkGGvaLdUGAqVwHDUAlzCnfQ32HcBHoxpGgLGWwgSmuwQAQ8t2nnf6HxE5S-2RNe8c17nd_qUk41b9gAn4Rwee2_eEcxNoEskaDb9lq1rXO875JrHC7-iYzPZ6cRdwEo2AdkxVVOjyPzbF06zESCe9HgMppOs6H_JnqQNekSFl5RN31pRzWsH9WtITV8ftO-5KQFQ6L0EEUpsZoMnY_fFCSZMm1WPp9fHoFEn4ek9OtBZ0ixqXxVIEX40.gfmgwuhBxfptabGILzAJnFMQ11p3b2aaixoWXd-NHpA&dib_tag=se&keywords=watch&qid=1734149945&sprefix=watc%2Caps%2C944&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1', 'https://www.amazon.com/Tensky-Android-Waterproof-Pedometer-Activity/dp/B0DBY8KXCR/ref=sr_1_13_sspa?dib=eyJ2IjoiMSJ9.AFIUHMISy7v70cr9d3Uv3W7CmeBqIZ0bFcWM8jT7D1vdc1s0BuCDkQeIO2-fftK-0RTAjp11Cfs1Foy-NVgHVZx85Yeq4LqSL4KWqF8zlF3hjvqiKkrVI9yrQeKslO-NszyYSTKHrI9weEvmvEiRqTLJYkRe8Np_1wYb57Nea2zQpwjgMcK1P2rGDMx9J8sd5tD210nuDVe0q9Fc6UENeBMqHQSKVnD6H2c0EbYnMewC-kfq0U6g5ZjKsV-aX4tdzdppgn2cEe3dcMPusHLQbcUuENXSHxjw83_D3rvtV30.tw1zhG32m4HA4c6MvGhwJoeARtGe4KvcPOTxUVX7QB8&dib_tag=se&keywords=watch&qid=1733455501&sr=8-13-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&th=1','https://www.amazon.com/Michael-Kors-Womens-Gold-Tone-MK3513/dp/B01BESQG9K/ref=sr_1_17?dib=eyJ2IjoiMSJ9.AFIUHMISy7v70cr9d3Uv3W7CmeBqIZ0bFcWM8jT7D1vdc1s0BuCDkQeIO2-fftK-0RTAjp11Cfs1Foy-NVgHVZx85Yeq4LqSL4KWqF8zlF3hjvqiKkrVI9yrQeKslO-NszyYSTKHrI9weEvmvEiRqTLJYkRe8Np_1wYb57Nea2zQpwjgMcK1P2rGDMx9J8sd5tD210nuDVe0q9Fc6UENeBMqHQSKVnD6H2c0EbYnMewC-kfq0U6g5ZjKsV-aX4tdzdppgn2cEe3dcMPusHLQbcUuENXSHxjw83_D3rvtV30.tw1zhG32m4HA4c6MvGhwJoeARtGe4KvcPOTxUVX7QB8&dib_tag=se&keywords=watch&qid=1733455501&sr=8-17&th=1', 'https://www.amazon.com/HAYLOU-Android-Watches-Fitness-Waterproof/dp/B09N6S6RFM/ref=sr_1_20_sspa?dib=eyJ2IjoiMSJ9.AFIUHMISy7v70cr9d3Uv3W7CmeBqIZ0bFcWM8jT7D1vdc1s0BuCDkQeIO2-fftK-0RTAjp11Cfs1Foy-NVgHVZx85Yeq4LqSL4KWqF8zlF3hjvqiKkrVI9yrQeKslO-NszyYSTKHrI9weEvmvEiRqTLJYkRe8Np_1wYb57Nea2zQpwjgMcK1P2rGDMx9J8sd5tD210nuDVe0q9Fc6UENeBMqHQSKVnD6H2c0EbYnMewC-kfq0U6g5ZjKsV-aX4tdzdppgn2cEe3dcMPusHLQbcUuENXSHxjw83_D3rvtV30.tw1zhG32m4HA4c6MvGhwJoeARtGe4KvcPOTxUVX7QB8&dib_tag=se&keywords=watch&qid=1733455501&sr=8-20-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&psc=1')

nameofproduct <- vector("list", length(urls))
names <- vector("list", length(urls))
ratings <- vector("list", length(urls))
dates <- vector("list", length(urls))
title <- vector("list", length(urls))
text <- vector("list", length(urls))
n <- vector("list", length(urls))
```

```{r}
df <- list()

for (i in seq_along(urls)) {
    session <- bow(urls[i], user_agent = "Educational")
    webpage <- scrape(session)
  
    
    nam <- webpage %>% html_nodes(".a-profile-name") %>% html_text()
    nam <- nam[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam, ignore.case = TRUE)]
    nam <- nam[nam != ""]
    n[[i]] <- nam
    name <- c() 
    non_amazon_seen <- FALSE  
    for (na in nam) {
      if (na == "Amazon Customer") {

        if (non_amazon_seen) {
          name <- c(name, na)
        }
      } else {
        name <- c(name, na)
        non_amazon_seen <- TRUE
        }
    }
    name <- name[!duplicated(name) | name == "Amazon Customer"]
    names[[i]] <- name
    
        nameofproduct[[i]] <-  webpage %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct[[i]] <- rep(nameofproduct[[i]], length.out = length(names[[i]]))
    
    rate <- webpage %>% html_nodes(".a-icon-alt") %>% html_text()
    rati <- rate[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate, ignore.case = TRUE)]
    rat <- gsub(" out of 5 stars", "", rati)
    rats <- rat
    if (length(rats) > length(name)) {
    rats <- tail(rats, length(name)) 
    } else if (length(rats) < length(name)) {
    rats <- c(rats, rep(NA, length(name) - length(rats)))
    }

    ratings[[i]] <- rats
    
    dat <- webpage %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date <- gsub("Reviewed.*on ", "", dat)
    dates[[i]] <- date

    titl <- webpage %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit <- gsub("Reviewed.*on ", "", titl)
    ti <- gsub(".*stars\\s*", "", tit)
    t <- gsub("\\s+", " ", ti)
    title[[i]] <- t

    tex <- webpage %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te <- gsub("\\n", " ", tex)
    t <- gsub("\\s+", " ", te)
    text[[i]] <- trimws(t)
}
```
```{r}
cate <- c("Category 1: WATCH", "Category 2", "Category 3", "Category 4", "Category 5")
category <- vector("list", length(cate))
for (i in seq_along(cate)) {
    category[[i]] <- cate[i]
}
```

```{r}
for (i in seq_along(cate)) {
    category[[i]] <- rep(category[[i]], length.out = length(names[[i]]))
}
```

```{r}
productnumbe <- c("Product 1", "Product 2", "Product 3", "Product 4", "Product 5", "Product 6", "Product 7", "Product 8", "Product 9", "Product 10")
productnumber <- vector("list", length(productnumbe))
for (i in seq_along(productnumbe)) {
    productnumber[[i]] <- productnumbe[i]
}
for (i in seq_along(urls)) {
    productnumber[[i]] <- rep(productnumber[[i]], length.out = length(names[[i]]))
}
```

```{r}

watch1 <- data.frame(Category = category[[1]],
                     Product_number = productnumber[[1]],
                      Name_of_Product = nameofproduct[[1]],
                      Userame = names[[1]],
                       Rating = ratings[[1]],
                       Date = dates[[1]],
                       Title_of_Review = title[[1]],
                       Text_of_Review = text[[1]],
                       stringsAsFactors = FALSE
                       )
head(watch1, 50)
watch1 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```



```{r}
nama <- names[[2]]
namez <- nama[!grepl("Amazon Customer|How to sleep monitoring", nama, ignore.case = TRUE)]
producto <- productnumber[[2]]
producto <- rep(producto, length.out = length(namez))
produc <- nameofproduct[[2]]
produc <- rep(produc, length.out = length(namez))
cater <- category[[1]]
ca <- rep(cater, length.out = length(namez))

ratingz <- ratings[[2]]
    if (length(ratingz) > length(namez)) {
    ratingz <- tail(ratingz, length(namez)) 
    } else if (length(ratingz) < length(namez)) {
    ratingz <- c(ratingz, rep(NA, length(namez) - length(ratingz)))
    }
```

```{r}
watch2 <- data.frame(Category = ca,
                     Product_number = producto,
                      Name_of_Product = produc,
                      Userame = namez,
                       Rating = ratingz,
                       Date = dates[[2]],
                       Title_of_Review = title[[2]],
                       Text_of_Review = text[[2]],
                       stringsAsFactors = FALSE
                       )
head(watch2, 50)
watch2 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama1 <- names[[3]]
namez1 <- nama1[!grepl("Fossil Men's Minimalist", nama1, ignore.case = TRUE)]
namez1 <- unique(namez1)
namez1 <- namez1[-1]
producto1 <- productnumber[[3]]
producto1 <- rep(producto1, length.out = length(namez1))
produc1 <- nameofproduct[[3]]
produc1 <- rep(produc1, length.out = length(namez1))
cater1 <- category[[1]]
ca1 <- rep(cater1, length.out = length(namez1))

ratingz1 <- ratings[[3]]
    if (length(ratingz1) > length(namez1)) {
    ratingz1 <- tail(ratingz1, length(namez1)) 
    } else if (length(ratingz) < length(namez1)) {
    ratingz1 <- c(ratingz1, rep(NA, length(namez1) - length(ratingz1)))
    }
```

```{r}
watch3 <- data.frame(Category = ca1,
                     Product_number = producto1,
                      Name_of_Product = produc1,
                      Userame = namez1,
                       Rating = ratingz1,
                       Date = dates[[3]],
                       Title_of_Review = title[[3]],
                       Text_of_Review = text[[3]],
                       stringsAsFactors = FALSE
                       )
head(watch3, 50)
watch3 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama2 <- names[[4]]
namez2 <- nama2[!grepl("Fossil Men's Grant", nama2, ignore.case = TRUE)]
namez2 <- namez2[-(1:2)]
producto2 <- productnumber[[4]]
producto2 <- rep(producto2, length.out = length(namez2))
produc2 <- nameofproduct[[4]]
produc2 <- rep(produc2, length.out = length(namez2))
cater2 <- category[[1]]
ca2 <- rep(cater2, length.out = length(namez2))

ratingz2 <- ratings[[4]]
    if (length(ratingz2) > length(namez2)) {
    ratingz2 <- tail(ratingz2, length(namez2)) 
    } else if (length(ratingz2) < length(namez2)) {
    ratingz2 <- c(ratingz2, rep(NA, length(namez2) - length(ratingz2)))
    }
```

```{r}
watch4 <- data.frame(Category = ca2,
                     Product_number = producto2,
                      Name_of_Product = produc2,
                      Userame = namez2,
                       Rating = ratingz2,
                       Date = dates[[4]],
                       Title_of_Review = title[[4]],
                       Text_of_Review = text[[4]],
                       stringsAsFactors = FALSE
                       )
head(watch4, 50)
watch4 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama3 <- names[[5]]
namez3 <- nama3[!grepl("Kids Watches Digital Sport Fitness Tracker LightPurple", nama3, ignore.case = TRUE)]
namez3 <- namez3[-(1:2)]
producto3 <- productnumber[[5]]
producto3 <- rep(producto3, length.out = length(namez3))
produc3 <- nameofproduct[[5]]
produc3 <- rep(produc3, length.out = length(namez3))
cater3 <- category[[1]]
ca3 <- rep(cater3, length.out = length(namez3))

ratingz3 <- ratings[[5]]
    if (length(ratingz3) > length(namez3)) {
    ratingz3 <- tail(ratingz3, length(namez3)) 
    } else if (length(ratingz3) < length(namez3)) {
    ratingz3<- c(ratingz3, rep(NA, length(namez3) - length(ratingz3)))
    }
```

```{r}
watch5 <- data.frame(Category = ca3,
                     Product_number = producto3,
                      Name_of_Product = produc3,
                      Userame = namez3,
                       Rating = ratingz3,
                       Date = dates[[5]],
                       Title_of_Review = title[[5]],
                       Text_of_Review = text[[5]],
                       stringsAsFactors = FALSE
                       )
head(watch5, 50)
watch5 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
names[[5]]
```


```{r}
nama4 <- n[[6]]
namez4 <- nama4[!grepl("Tensky smart watch", nama4, ignore.case = TRUE)]
namez4 <- namez4[-(1:2)]
namez4 <- unique(namez4)
nr <- which(namez4 == "Latrisha Love") + 1
namez4 <- append(namez4, "Placeholder", after = nr - 1)
producto4 <- productnumber[[6]]
producto4 <- rep(producto4, length.out = length(namez4))
produc4 <- nameofproduct[[6]]
produc4 <- rep(produc4, length.out = length(namez4))
cater4 <- category[[1]]
ca4 <- rep(cater4, length.out = length(namez4))

ratingz4 <- ratings[[6]]
    if (length(ratingz4) > length(namez4)) {
    ratingz4 <- tail(ratingz4, length(namez4)) 
    } else if (length(ratingz4) < length(namez4)) {
    ratingz4<- c(ratingz4, rep(NA, length(namez4) - length(ratingz4)))
    }
```
```{r}
watch6 <- data.frame(Category = ca4,
                     Product_number = producto4,
                      Name_of_Product = produc4,
                      Userame = namez4,
                       Rating = ratingz4,
                       Date = dates[[6]],
                       Title_of_Review = title[[6]],
                       Text_of_Review = text[[6]],
                       stringsAsFactors = FALSE
                       )
head(watch6, 50)
watch6 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama5 <- names[[7]]
namez5 <- nama5[!grepl("Michael Kors Women's", nama5, ignore.case = TRUE)]
namez5 <- namez5[-(1:2)]
producto5 <- productnumber[[7]]
producto5 <- rep(producto5, length.out = length(namez5))
produc5 <- nameofproduct[[7]]
produc5 <- rep(produc3, length.out = length(namez5))
cater5 <- category[[1]]
ca5 <- rep(cater5, length.out = length(namez5))

ratingz5 <- ratings[[7]]
    if (length(ratingz5) > length(namez5)) {
    ratingz5 <- tail(ratingz5, length(namez5)) 
    } else if (length(ratingz5) < length(namez5)) {
    ratingz5<- c(ratingz5, rep(NA, length(namez5) - length(ratingz5)))
    }
```

```{r}
watch7 <- data.frame(Category = ca5,
                     Product_number = producto5,
                      Name_of_Product = produc5,
                      Userame = namez5,
                       Rating = ratingz5,
                       Date = dates[[7]],
                       Title_of_Review = title[[7]],
                       Text_of_Review = text[[7]],
                       stringsAsFactors = FALSE
                       )
head(watch7, 50)
watch7 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
nama6 <- names[[8]]
namez6 <- nama6[!grepl("How to Use", nama6, ignore.case = TRUE)]
namez6 <- namez6[-(1:2)]
producto6 <- productnumber[[8]]
producto6 <- rep(producto6, length.out = length(namez6))
produc6 <- nameofproduct[[8]]
produc6 <- rep(produc6, length.out = length(namez6))
cater6 <- category[[1]]
ca6 <- rep(cater6, length.out = length(namez6))

ratingz6 <- ratings[[8]]
    if (length(ratingz6) > length(namez6)) {
    ratingz6 <- tail(ratingz6, length(namez6)) 
    } else if (length(ratingz6) < length(namez6)) {
    ratingz6<- c(ratingz6, rep(NA, length(namez6) - length(ratingz6)))
    }
```

```{r}
watch8 <- data.frame(Category = ca6,
                     Product_number = producto6,
                      Name_of_Product = produc6,
                      Userame = namez6,
                       Rating = ratingz6,
                       Date = dates[[8]],
                       Title_of_Review = title[[8]],
                       Text_of_Review = text[[8]],
                       stringsAsFactors = FALSE
                       )
head(watch8, 50)
watch8 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```

```{r}
urls1b <- c('https://www.amazon.com/Anne-Klein-Womens-105491SVTT-Two-Tone/dp/B000U5O5XI/ref=sr_1_58?crid=39E09RNS3R2FN&dib=eyJ2IjoiMSJ9.AFIUHMISy7v70cr9d3Uv3W7CmeBqIZ0bFcWM8jT7D1vdc1s0BuCDkQeIO2-fftK-0RTAjp11Cfs1Foy-NVgHVZx85Yeq4LqSL4KWqF8zlF1_FDP4H4gsHPIgTBXMrEYldQatPuonsofOdIV33oqyhTLJYkRe8Np_1wYb57Nea2xJR84RbAIsWpVeaBopTZ--GRZlSWyD7dMsfKYymAR7Tcxhj16e4NjFdXLtmgOmyuJWxJLOspsadWcKEyxdBJF-q8eL041Q-RSuFZjWiFV_M_C4e271J6Ljo7a4ybkZJas.ZJvF9u0l_vFu4jFNnAyjzopMvGXtwjJdTgw_2zLnZUA&dib_tag=se&keywords=watch&qid=1733474482&sprefix=watch%2Caps%2C924&sr=8-58&th=1', 'https://www.amazon.com/BENYAR-Waterproof-Multifunction-Chronograph-Wristwatches/dp/B07X7MC5LQ/ref=sr_1_55?crid=39E09RNS3R2FN&dib=eyJ2IjoiMSJ9.AFIUHMISy7v70cr9d3Uv3W7CmeBqIZ0bFcWM8jT7D1vdc1s0BuCDkQeIO2-fftK-0RTAjp11Cfs1Foy-NVgHVZx85Yeq4LqSL4KWqF8zlF1_FDP4H4gsHPIgTBXMrEYldQatPuonsofOdIV33oqyhTLJYkRe8Np_1wYb57Nea2xJR84RbAIsWpVeaBopTZ--GRZlSWyD7dMsfKYymAR7Tcxhj16e4NjFdXLtmgOmyuJWxJLOspsadWcKEyxdBJF-q8eL041Q-RSuFZjWiFV_M_C4e271J6Ljo7a4ybkZJas.ZJvF9u0l_vFu4jFNnAyjzopMvGXtwjJdTgw_2zLnZUA&dib_tag=se&keywords=watch&qid=1733474482&sprefix=watch%2Caps%2C924&sr=8-55&th=1')
nameofproduct1b <- vector("list", length(urls1b))
names1b <- vector("list", length(urls1b))
ratings1b <- vector("list", length(urls1b))
dates1b <- vector("list", length(urls1b))
title1b <- vector("list", length(urls1b))
text1b <- vector("list", length(urls1b))
n1b <- vector("list", length(urls1b))
```

```{r}
df <- list()

for (i in seq_along(urls1b)) {
    session <- bow(urls1b[i], user_agent = "Educational")
    webpage1b <- scrape(session)
  
    
    nam1b <- webpage1b %>% html_nodes(".a-profile-name") %>% html_text()
    nam1b <- nam1b[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam1b, ignore.case = TRUE)]
    nam1b <- nam1b[nam1b != ""]
    n1b[[i]] <- nam1b
    name1b <- c() 
    non_amazon_seen1b <- FALSE  
    for (na1b in nam1b) {
      if (na1b == "Amazon Customer") {

        if (non_amazon_seen1b) {
          name1b <- c(name1b, na1b)
        }
      } else {
        name1b <- c(name1b, na1b)
        non_amazon_seen1b <- TRUE
        }
    }
    name1b <- name1b[!duplicated(name1b) | name1b == "Amazon Customer"]
    names1b[[i]] <- name1b
    
        nameofproduct1b[[i]] <-  webpage1b %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct1b[[i]] <- rep(nameofproduct1b[[i]], length.out = length(names1b[[i]]))
    
    rate1b <- webpage1b %>% html_nodes(".a-icon-alt") %>% html_text()
    rati1b <- rate1b[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate1b, ignore.case = TRUE)]
    rat1b <- gsub(" out of 5 stars", "", rati1b)
    rats1b <- rat1b
    if (length(rats1b) > length(name1b)) {
    rats1b <- tail(rats1b, length(name1b)) 
    } else if (length(rats1b) < length(name1b)) {
    rats1b <- c(rats1b, rep(NA, length(name1b) - length(rats1b)))
    }

    ratings1b[[i]] <- rats1b
    
    dat1b <- webpage1b %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date1b <- gsub("Reviewed.*on ", "", dat1b)
    dates1b[[i]] <- date1b

    titl1b <- webpage1b %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit1b <- gsub("Reviewed.*on ", "", titl1b)
    ti1b <- gsub(".*stars\\s*", "", tit1b)
    t1b <- gsub("\\s+", " ", ti1b)
    title1b[[i]] <- t1b

    tex1b <- webpage1b %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te1b <- gsub("\\n", " ", tex1b)
    t1b <- gsub("\\s+", " ", te1b)
    text1b[[i]] <- trimws(t1b)
}
```

```{r}
cate1b <- c("Category 1: WATCH", "Category 2:", "Category 3:", "Category 4:", "Category 5:")
category1b <- vector("list", length(cate1b))
for (i in seq_along(cate1b)) {
    category1b[[i]] <- cate1b[i]
}
```

```{r}
for (i in seq_along(urls1b)) {
    category1b[[i]] <- rep(category1b[[i]], length.out = length(names1b[[i]]))
}
```

```{r}
productnumbe1b <- c("Product 9", "Product 10")
productnumber1b <- vector("list", length(productnumbe1b))
for (i in seq_along(productnumbe1b)) {
    productnumber1b[[i]] <- productnumbe1b[i]
}
for (i in seq_along(urls1b)) {
    productnumber1b[[i]] <- rep(productnumber1b[[i]], length.out = length(names1b[[i]]))
}
```

```{r}
nama7 <- names1b[[1]]
namez7 <- nama7[!grepl("Anne Klein Women's", nama7, ignore.case = TRUE)]
namez7 <- namez7[-(1:2)]
producto7 <- productnumber1b[[1]]
producto7 <- rep(producto7, length.out = length(namez7))
produc7 <- nameofproduct1b[[1]]
produc7 <- rep(produc7, length.out = length(namez7))
cater7 <- category1b[[1]]
ca7 <- rep(cater7, length.out = length(namez7))

ratingz7 <- ratings1b[[1]]
    if (length(ratingz7) > length(namez7)) {
    ratingz7 <- tail(ratingz7, length(namez7)) 
    } else if (length(ratingz7) < length(namez7)) {
    ratingz7<- c(ratingz7, rep(NA, length(namez7) - length(ratingz7)))
    }
```

```{r}
watch9 <- data.frame(Category = ca7,
                     Product_number = producto7,
                      Name_of_Product = produc7,
                      Userame = namez7,
                       Rating = ratingz7,
                       Date = dates1b[[1]],
                       Title_of_Review = title1b[[1]],
                       Text_of_Review = text1b[[1]],
                       stringsAsFactors = FALSE
                       )
head(watch9, 50)
watch9 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```
```{r}
nama8 <- names1b[[2]]
namez8 <- nama8[!grepl("BENYAR- 5160", nama8, ignore.case = TRUE)]
namez8 <- namez8[-(1:2)]
producto8 <- productnumber1b[[2]]
producto8 <- rep(producto8, length.out = length(namez8))
produc8 <- nameofproduct1b[[2]]
produc8 <- rep(produc8, length.out = length(namez8))
cater8 <- category1b[[1]]
ca8 <- rep(cater8, length.out = length(namez8))

ratingz8 <- ratings1b[[2]]
    if (length(ratingz8) > length(namez8)) {
    ratingz8 <- tail(ratingz8, length(namez8)) 
    } else if (length(ratingz8) < length(namez8)) {
    ratingz8<- c(ratingz8, rep(NA, length(namez8) - length(ratingz8)))
    }
```

```{r}
watch10 <- data.frame(Category = ca8,
                     Product_number = producto8,
                      Name_of_Product = produc8,
                      Userame = namez8,
                       Rating = ratingz8,
                       Date = dates1b[[2]],
                       Title_of_Review = title1b[[2]],
                       Text_of_Review = text1b[[2]],
                       stringsAsFactors = FALSE
                       )
head(watch10, 50)
watch10 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```


```{r}
urls2 <- c('https://www.amazon.com/CeraVe-Moisturizing-Cream-Daily-Moisturizer/dp/B00TTD9BRC/ref=sr_1_8?crid=SF0220A25D3K&dib=eyJ2IjoiMSJ9.O6Tm7-AU7OoiTr5bgfcJGTGXdc_DYBkva-A087l3wY9Aq6B9LUbWUWUd9XPFeR2RSDUKHOWHUWVQrBkPTA_wWplnQ68RexSh2dfo0fP_beha-CHUsSmp2ICfUnYZJxIik-Ig0vvXXnT2iFQsnBkIst-6iOtuobsgDL3B2KOzMln6X2bcg1R5qabIetVP_LKVAL6HZKNNzH4tC5HvJuVh1fYexC5aNj2lG36pkhp-5mj9zoVCgaBkKbPzHyv0HlNnh3cVO-1Gm7pMF0dztdjPvZ2vVYXzqvUz0E5ZsyOTbY8.0lF2DQuZ9wsYvoaZRT6Yz6T_fWH-tJklySVL4nJ3C2o&dib_tag=se&keywords=skin%2Bcare&qid=1733477546&sprefix=Skin%2Caps%2C652&sr=8-8&th=1', 'https://www.amazon.com/CeraVe-Moisturizing-Cream-Daily-Moisturizer/dp/B00TTD9BRC/ref=sr_1_8?crid=SF0220A25D3K&dib=eyJ2IjoiMSJ9.O6Tm7-AU7OoiTr5bgfcJGTGXdc_DYBkva-A087l3wY9Aq6B9LUbWUWUd9XPFeR2RSDUKHOWHUWVQrBkPTA_wWplnQ68RexSh2dfo0fP_beha-CHUsSmp2ICfUnYZJxIik-Ig0vvXXnT2iFQsnBkIst-6iOtuobsgDL3B2KOzMln6X2bcg1R5qabIetVP_LKVAL6HZKNNzH4tC5HvJuVh1fYexC5aNj2lG36pkhp-5mj9zoVCgaBkKbPzHyv0HlNnh3cVO-1Gm7pMF0dztdjPvZ2vVYXzqvUz0E5ZsyOTbY8.0lF2DQuZ9wsYvoaZRT6Yz6T_fWH-tJklySVL4nJ3C2o&dib_tag=se&keywords=skin%2Bcare&qid=1733477546&sprefix=Skin%2Caps%2C652&sr=8-8&th=1', 'https://www.amazon.com/Choice-SKIN-PERFECTING-Duo-Facial-Exfoliants-Exfoliators/dp/B07TK4D5VD/ref=sxin_16_pa_sp_search_thematic_sspa?content-id=amzn1.sym.138b1752-1feb-4f66-9678-fccc5f256ade%3Aamzn1.sym.138b1752-1feb-4f66-9678-fccc5f256ade&crid=1HHIAD37XPLJR&cv_ct_cx=skincare&keywords=skincare&pd_rd_i=B07TK4D5VD&pd_rd_r=d3dfb790-e2b5-4745-af46-83da49ea0913&pd_rd_w=AR2zi&pd_rd_wg=5WrTp&pf_rd_p=138b1752-1feb-4f66-9678-fccc5f256ade&pf_rd_r=TK6QW1F4P28VDQ0RGZ3W&qid=1733489813&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sprefix=skincare%2Caps%2C984&sr=1-2-9428117c-b940-4daa-97e9-ad363ada7940-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9zZWFyY2hfdGhlbWF0aWM&th=1', 'https://www.amazon.com/Glow-Recipe-Watermelon-Pore-Tight-Facial/dp/B093Z2HVJC/ref=sr_1_16?crid=1HHIAD37XPLJR&dib=eyJ2IjoiMSJ9.SBQu3fmTy42aIy5ukmO0HOfUMyb5Nqgm2eSs5jM0tfdZbZs5GJIgmGyjUqRBIy66dqc4Y7fZNPAaa6_DX00fbwgqLSSgoqlSGhOOKQjs9vJweQExJJQG0GYHJp91YIaTdykxrot9oWQwxflBakx24xm7h9gMzwm5RKxAeiwBM5DgtCKcAh3_ITRFlnb1SlznE7Eb2ZgV2jFQaQhAS6lz1hcz-Bs0TapF0thWmxIlnUGZ86tY4fjUFhBpkHF3njQIOwlVm3o_DsV_2looAzLQHDaA00kYtHXpH17c2VCWqKc.8EdXnpwLWXc9Z9WcN90aVUV3vk96PGvyKBQBXRx4jfc&dib_tag=se&keywords=skincare&qid=1733489813&sprefix=skincare%2Caps%2C984&sr=8-16', 'https://www.amazon.com/Youth-People-Kale-Superfood-Cleanser/dp/B018A0BO92/ref=sr_1_18?crid=1HHIAD37XPLJR&dib=eyJ2IjoiMSJ9.SBQu3fmTy42aIy5ukmO0HOfUMyb5Nqgm2eSs5jM0tfdZbZs5GJIgmGyjUqRBIy66dqc4Y7fZNPAaa6_DX00fbwgqLSSgoqlSGhOOKQjs9vJweQExJJQG0GYHJp91YIaTdykxrot9oWQwxflBakx24xm7h9gMzwm5RKxAeiwBM5DgtCKcAh3_ITRFlnb1SlznE7Eb2ZgV2jFQaQhAS6lz1hcz-Bs0TapF0thWmxIlnUGZ86tY4fjUFhBpkHF3njQIOwlVm3o_DsV_2looAzLQHDaA00kYtHXpH17c2VCWqKc.8EdXnpwLWXc9Z9WcN90aVUV3vk96PGvyKBQBXRx4jfc&dib_tag=se&keywords=skincare&qid=1733489813&sprefix=skincare%2Caps%2C984&sr=8-18&th=1', 'https://www.amazon.com/grace-stella-Purple-Treatment-Gels/dp/B0CPT8W3RV/ref=sr_1_19_sspa?crid=1HHIAD37XPLJR&dib=eyJ2IjoiMSJ9.SBQu3fmTy42aIy5ukmO0HOfUMyb5Nqgm2eSs5jM0tfdZbZs5GJIgmGyjUqRBIy66dqc4Y7fZNPAaa6_DX00fbwgqLSSgoqlSGhOOKQjs9vJweQExJJQG0GYHJp91YIaTdykxrot9oWQwxflBakx24xm7h9gMzwm5RKxAeiwBM5DgtCKcAh3_ITRFlnb1SlznE7Eb2ZgV2jFQaQhAS6lz1hcz-Bs0TapF0thWmxIlnUGZ86tY4fjUFhBpkHF3njQIOwlVm3o_DsV_2looAzLQHDaA00kYtHXpH17c2VCWqKc.8EdXnpwLWXc9Z9WcN90aVUV3vk96PGvyKBQBXRx4jfc&dib_tag=se&keywords=skincare&qid=1733489813&sprefix=skincare%2Caps%2C984&sr=8-19-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&smid=A1IRZ7664JSWXN&th=1', 'https://www.amazon.com/BAIMEI-Roller-Massager-Treatment-Routine/dp/B08RD6S5HF/ref=sr_1_24?crid=1HHIAD37XPLJR&dib=eyJ2IjoiMSJ9.SBQu3fmTy42aIy5ukmO0HOfUMyb5Nqgm2eSs5jM0tfdZbZs5GJIgmGyjUqRBIy66dqc4Y7fZNPAaa6_DX00fbwgqLSSgoqlSGhOOKQjs9vJweQExJJQG0GYHJp91YIaTdykxrot9oWQwxflBakx24xm7h9gMzwm5RKxAeiwBM5DgtCKcAh3_ITRFlnb1SlznE7Eb2ZgV2jFQaQhAS6lz1hcz-Bs0TapF0thWmxIlnUGZ86tY4fjUFhBpkHF3njQIOwlVm3o_DsV_2looAzLQHDaA00kYtHXpH17c2VCWqKc.8EdXnpwLWXc9Z9WcN90aVUV3vk96PGvyKBQBXRx4jfc&dib_tag=se&keywords=skincare&qid=1733489813&sprefix=skincare%2Caps%2C984&sr=8-24&th=1')

nameofproduct2 <- vector("list", length(urls2))
names2 <- vector("list", length(urls2))
ratings2 <- vector("list", length(urls2))
dates2 <- vector("list", length(urls2))
title2 <- vector("list", length(urls2))
text2 <- vector("list", length(urls2))
n2 <- vector("list", length(urls2))
```

```{r}
df <- list()

for (i in seq_along(urls2)) {
    session <- bow(urls2[i], user_agent = "Educational")
    webpage2 <- scrape(session)
  
    
    nam2 <- webpage2 %>% html_nodes(".a-profile-name") %>% html_text()
    nam2 <- nam2[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam2, ignore.case = TRUE)]
    nam2 <- nam2[nam2 != ""]
    n2[[i]] <- nam2
    name2 <- c() 
    non_amazon_seen2 <- FALSE  
    for (na2 in nam2) {
      if (na2 == "Amazon Customer") {

        if (non_amazon_seen2) {
          name2 <- c(name2, na2)
        }
      } else {
        name2 <- c(name2, na2)
        non_amazon_seen2 <- TRUE
        }
    }
    name2 <- name2[!duplicated(name2) | name2 == "Amazon Customer"]
    names2[[i]] <- name2
    
        nameofproduct2[[i]] <-  webpage2 %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct2[[i]] <- rep(nameofproduct2[[i]], length.out = length(names2[[i]]))
    
    rate2 <- webpage2 %>% html_nodes(".a-icon-alt") %>% html_text()
    rati2 <- rate2[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate2, ignore.case = TRUE)]
    rat2 <- gsub(" out of 5 stars", "", rati2)
    rats2 <- rat2
    if (length(rats2) > length(name2)) {
    rats2 <- tail(rats2, length(name2)) 
    } else if (length(rats2) < length(name2)) {
    rats2 <- c(rats2, rep(NA, length(name2) - length(rats2)))
    }

    ratings2[[i]] <- rats2
    
    dat2 <- webpage2 %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date2 <- gsub("Reviewed.*on ", "", dat2)
    dates2[[i]] <- date2

    titl2 <- webpage2 %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit2 <- gsub("Reviewed.*on ", "", titl2)
    ti2 <- gsub(".*stars\\s*", "", tit2)
    t2 <- gsub("\\s+", " ", ti2)
    title2[[i]] <- t2

    tex2 <- webpage2 %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te2 <- gsub("\\n", " ", tex2)
    t2 <- gsub("\\s+", " ", te2)
    text2[[i]] <- trimws(t2)
}
```

```{r}
cate2 <- c("Category 1: WATCH", "Category 2: SKINCARE", "Category 3", "Category 4", "Category 5")
category2 <- vector("list", length(cate2))
for (i in seq_along(cate2)) {
    category2[[i]] <- cate2[i]
}
```

```{r}
for (i in seq_along(cate2)) {
    category2[[i]] <- rep(category2[[i]], length.out = length(names2[[i]]))
}
```

```{r}
productnumbe2 <- c("Product 1", "Product 2", "Product 3", "Product 4", "Product 5", "Product 6", "Product 7", "Product 8", "Product 9", "Product 10")
productnumber2 <- vector("list", length(productnumbe2))
for (i in seq_along(productnumbe2)) {
    productnumber2[[i]] <- productnumbe2[i]
}
for (i in seq_along(urls2)) {
    productnumber2[[i]] <- rep(productnumber2[[i]], length.out = length(names2[[i]]))
}
```

```{r}
urls2b <- c('https://www.amazon.com/dp/B0973QK1JB/ref=sspa_dk_detail_2?psc=1&pd_rd_i=B0973QK1JB&pd_rd_w=2Lodt&content-id=amzn1.sym.10c716f0-b18a-473a-9d6a-5d87bc47ef1e&pf_rd_p=10c716f0-b18a-473a-9d6a-5d87bc47ef1e&pf_rd_r=296EN055XHBREDFKWDX3&pd_rd_wg=KrU67&pd_rd_r=0761f314-454f-4e88-8d38-2b0523af5445&s=beauty&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM', 'https://www.amazon.com/Wrinkles-Cleanser-Skincare-Christmas-Stocking/dp/B0CG3FYS43/ref=slsr_d_dpds_fsdpnewarrivals_fa_xcat_fixed_d_sccl_3_1/146-7533384-2764569?pd_rd_w=O1wmN&content-id=amzn1.sym.ccf81fad-ab20-46d4-9d07-e05fbc75bde6&pf_rd_p=ccf81fad-ab20-46d4-9d07-e05fbc75bde6&pf_rd_r=0J568DTNTDQDPSWR0YR5&pd_rd_wg=xjTdU&pd_rd_r=5b052182-785c-469f-bba7-b2c30bf49393&pd_rd_i=B0CG3FYS43&th=1', 'https://www.amazon.com/Medicube-Collagen-Wrapping-Elasticity-Hydration/dp/B0BRMYHMS5/ref=sr_1_33?crid=1HHIAD37XPLJR&dib=eyJ2IjoiMSJ9.SBQu3fmTy42aIy5ukmO0HOfUMyb5Nqgm2eSs5jM0tfdZbZs5GJIgmGyjUqRBIy66dqc4Y7fZNPAaa6_DX00fbwgqLSSgoqlSGhOOKQjs9vJweQExJJQG0GYHJp91YIaTdykxrot9oWQwxflBakx24xm7h9gMzwm5RKxAeiwBM5DgtCKcAh3_ITRFlnb1SlznE7Eb2ZgV2jFQaQhAS6lz1hcz-Bs0TapF0thWmxIlnUGZ86tY4fjUFhBpkHF3njQIOwlVm3o_DsV_2looAzLQHDaA00kYtHXpH17c2VCWqKc.8EdXnpwLWXc9Z9WcN90aVUV3vk96PGvyKBQBXRx4jfc&dib_tag=se&keywords=skincare&qid=1733489813&sprefix=skincare%2Caps%2C984&sr=8-33')
nameofproduct2b <- vector("list", length(urls2b))
names2b <- vector("list", length(urls2b))
ratings2b <- vector("list", length(urls2b))
dates2b <- vector("list", length(urls2b))
title2b <- vector("list", length(urls2b))
text2b <- vector("list", length(urls2b))
n2b <- vector("list", length(urls2b))
```

```{r}
df <- list()

for (i in seq_along(urls2b)) {
    session <- bow(urls2b[i], user_agent = "Educational")
    webpage2b <- scrape(session)
  
    
    nam2b <- webpage2b %>% html_nodes(".a-profile-name") %>% html_text()
    nam2b <- nam2b[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam2b, ignore.case = TRUE)]
    nam2b <- nam2b[nam2b != ""]
    n2b[[i]] <- nam2b
    name2b <- c() 
    non_amazon_seen2b <- FALSE  
    for (na2b in nam2b) {
      if (na2b == "Amazon Customer") {

        if (non_amazon_seen2b) {
          name2b <- c(name2b, na2b)
        }
      } else {
        name2b <- c(name2b, na2b)
        non_amazon_seen2b <- TRUE
        }
    }
    name2b <- name2b[!duplicated(name2b) | name2b == "Amazon Customer"]
    names2b[[i]] <- name2b
    
        nameofproduct2b[[i]] <-  webpage2b %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct2b[[i]] <- rep(nameofproduct2b[[i]], length.out = length(names2b[[i]]))
    
    rate2b <- webpage2b %>% html_nodes(".a-icon-alt") %>% html_text()
    rati2b <- rate2b[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate2b, ignore.case = TRUE)]
    rat2b <- gsub(" out of 5 stars", "", rati2b)
    rats2b <- rat2b
    if (length(rats2b) > length(name2b)) {
    rats2b <- tail(rats2b, length(name2b)) 
    } else if (length(rats2b) < length(name2b)) {
    rats2b <- c(rats2b, rep(NA, length(name2b) - length(rats2b)))
    }

    ratings2b[[i]] <- rats2b
    
    dat2b <- webpage2b %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date2b <- gsub("Reviewed.*on ", "", dat2b)
    dates2b[[i]] <- date2b

    titl2b <- webpage2b %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit2b <- gsub("Reviewed.*on ", "", titl2b)
    ti2b <- gsub(".*stars\\s*", "", tit2b)
    t2b <- gsub("\\s+", " ", ti2b)
    title2b[[i]] <- t2b

    tex2b <- webpage2b %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te2b <- gsub("\\n", " ", tex2b)
    t2b <- gsub("\\s+", " ", te2b)
    text2b[[i]] <- trimws(t2b)
}
```

```{r}
cate2b <- c("Category 1: WATCH", "Category 2: SKINCARE", "Category 3:", "Category 4:", "Category 5:")
category2b <- vector("list", length(cate2b))
for (i in seq_along(cate2b)) {
    category2b[[i]] <- cate2b[i]
}
```

```{r}
for (i in seq_along(urls2b)) {
    category2b[[i]] <- rep(category2b[[i]], length.out = length(names2b[[i]]))
}
```

```{r}
productnumbe2b <- c("Product 8", "Product 9", "Product 10")
productnumber2b <- vector("list", length(productnumbe2b))
for (i in seq_along(productnumbe2b)) {
    productnumber2b[[i]] <- productnumbe2b[i]
}
```

```{r}
for (i in seq_along(productnumber2b)) {
    productnumber2b[[i]] <- rep(productnumber2b[[i]], length.out = length(names2b[[i]]))
}
```

```{r}
nama9 <- names2[[1]]
namez9 <- nama9[!grepl("Moisturizing Cream", nama9, ignore.case = TRUE)]
namez9 <- namez9[-(1:2)]
producto9 <- productnumber2[[1]]
producto9 <- rep(producto9, length.out = length(namez9))
produc9 <- nameofproduct2[[1]]
produc9 <- rep(produc9, length.out = length(namez9))
cater9 <- category2[[2]]
ca9 <- rep(cater9, length.out = length(namez9))

ratingz9 <- ratings2[[1]]
    if (length(ratingz9) > length(namez9)) {
    ratingz9 <- tail(ratingz9, length(namez9)) 
    } else if (length(ratingz9) < length(namez9)) {
    ratingz9<- c(ratingz9, rep(NA, length(namez9) - length(ratingz9)))
    }
```

```{r}
skincare10 <- data.frame(Category = ca9,
                     Product_number = producto9,
                      Name_of_Product = produc9,
                      Userame = namez9,
                       Rating = ratingz9,
                       Date = dates2[[1]],
                       Title_of_Review = title2[[1]],
                       Text_of_Review = text2[[1]],
                       stringsAsFactors = FALSE
                       )
head(skincare10, 50)
```

```{r}
nama10 <- names2[[2]]
namez10 <- nama10[!grepl("Moisturizing Cream", nama10, ignore.case = TRUE)]
namez10 <- namez10[-(1:2)]
producto10 <- productnumber2[[2]]
producto10 <- rep(producto10, length.out = length(namez10))
produc10 <- nameofproduct2[[2]]
produc10 <- rep(produc10, length.out = length(namez10))
cater10 <- category2[[2]]
ca10 <- rep(cater10, length.out = length(namez10))

ratingz10 <- ratings2[[2]]
    if (length(ratingz10) > length(namez10)) {
    ratingz10 <- tail(ratingz10, length(namez10)) 
    } else if (length(ratingz10) < length(namez10)) {
    ratingz10<- c(ratingz10, rep(NA, length(namez10) - length(ratingz10)))
    }
```

```{r}
skincare2 <- data.frame(Category = ca10,
                     Product_number = producto10,
                      Name_of_Product = produc10,
                      Userame = namez10,
                       Rating = ratingz10,
                       Date = dates2[[2]],
                       Title_of_Review = title2[[2]],
                       Text_of_Review = text2[[2]],
                       stringsAsFactors = FALSE
                       )
head(skincare2, 50)
```

```{r}
nama11 <- names2[[3]]
namez11 <- nama11[!grepl("Paula's Choice SKIN", nama11, ignore.case = TRUE)]
namez11 <- namez11[-(1:2)]
producto11 <- productnumber2[[3]]
producto11 <- rep(producto11, length.out = length(namez11))
produc11 <- nameofproduct2[[3]]
produc11 <- rep(produc11, length.out = length(namez11))
cater11 <- category2[[2]]
ca11 <- rep(cater11, length.out = length(namez11))

ratingz11 <- ratings2[[3]]
    if (length(ratingz11) > length(namez11)) {
    ratingz11 <- tail(ratingz11, length(namez11)) 
    } else if (length(ratingz11) < length(namez11)) {
    ratingz11<- c(ratingz11, rep(NA, length(namez11) - length(ratingz11)))
    }
```

```{r}
skincare3 <- data.frame(Category = ca11,
                     Product_number = producto11,
                      Name_of_Product = produc11,
                      Userame = namez11,
                       Rating = ratingz11,
                       Date = dates2[[3]],
                       Title_of_Review = title2[[3]],
                       Text_of_Review = text2[[3]],
                       stringsAsFactors = FALSE
                       )
head(skincare3, 50)
```

```{r}
nama12 <- names2[[4]]
namez12 <- nama12[!grepl("Glow Recipe - Watermelon", nama12, ignore.case = TRUE)]
namez12 <- namez12[-(1:2)]
producto12 <- productnumber2[[4]]
producto12 <- rep(producto12, length.out = length(namez12))
produc12 <- nameofproduct2[[4]]
produc12 <- rep(produc12, length.out = length(namez12))
cater12 <- category2[[2]]
ca12 <- rep(cater12, length.out = length(namez12))

ratingz12 <- ratings2[[4]]
    if (length(ratingz12) > length(namez12)) {
    ratingz12 <- tail(ratingz12, length(namez12)) 
    } else if (length(ratingz12) < length(namez12)) {
    ratingz12<- c(ratingz12, rep(NA, length(namez12) - length(ratingz12)))
    }
```

```{r}
skincare4 <- data.frame(Category = ca12,
                     Product_number = producto12,
                      Name_of_Product = produc12,
                      Userame = namez12,
                       Rating = ratingz12,
                       Date = dates2[[4]],
                       Title_of_Review = title2[[4]],
                       Text_of_Review = text2[[4]],
                       stringsAsFactors = FALSE
                       )
head(skincare4, 50)
```

```{r}
nama13 <- names2[[5]]
namez13 <- nama13[!grepl("YTTP Superfood Cleanser", nama13, ignore.case = TRUE)]
namez13 <- namez13[-(1:2)]
producto13 <- productnumber2[[5]]
producto13 <- rep(producto13, length.out = length(namez13))
produc13 <- nameofproduct2[[5]]
produc13 <- rep(produc13, length.out = length(namez13))
cater13 <- category2[[2]]
ca13 <- rep(cater13, length.out = length(namez13))

ratingz13 <- ratings2[[5]]
    if (length(ratingz13) > length(namez13)) {
    ratingz13 <- tail(ratingz13, length(namez13)) 
    } else if (length(ratingz13) < length(namez13)) {
    ratingz13<- c(ratingz13, rep(NA, length(namez13) - length(ratingz13)))
    }
```

```{r}
skincare5 <- data.frame(Category = ca13,
                     Product_number = producto13,
                      Name_of_Product = produc13,
                      Userame = namez13,
                       Rating = ratingz13,
                       Date = dates2[[5]],
                       Title_of_Review = title2[[5]],
                       Text_of_Review = text2[[5]],
                       stringsAsFactors = FALSE
                       )
head(skincare5, 50)
```

```{r}
nama14 <- n2[[6]]
namez14 <- nama14[!grepl("G&S TV Ad Video", nama14, ignore.case = TRUE)]
namez14 <- namez14[-(1:2)]
namez14 <- unique(namez14)
producto14 <- productnumber2[[6]]
producto14 <- rep(producto14, length.out = length(namez14))
produc14 <- nameofproduct2[[6]]
produc14 <- rep(produc14, length.out = length(namez14))
cater14 <- category2[[2]]
ca14 <- rep(cater14, length.out = length(namez14))

ratingz14 <- ratings2[[6]]
    if (length(ratingz14) > length(namez14)) {
    ratingz14 <- tail(ratingz14, length(namez14)) 
    } else if (length(ratingz14) < length(namez14)) {
    ratingz14 <- c(ratingz14, rep(NA, length(namez14) - length(ratingz14)))
    }
```

```{r}
skincare6 <- data.frame(Category = ca14,
                     Product_number = producto14,
                      Name_of_Product = produc14,
                      Userame = namez14,
                       Rating = ratingz14,
                       Date = dates2[[6]],
                       Title_of_Review = title2[[6]],
                       Text_of_Review = text2[[6]],
                       stringsAsFactors = FALSE
                       )
head(skincare6, 50)
```

```{r}
nama15 <- names2[[7]]
namez15 <- nama15[!grepl("BAIMEI jade roller", nama15, ignore.case = TRUE)]
namez15 <- namez15[-(1:2)]
producto15 <- productnumber2[[7]]
producto15 <- rep(producto15, length.out = length(namez15))
produc15 <- nameofproduct2[[7]]
produc15 <- rep(produc15, length.out = length(namez15))
cater15 <- category2[[2]]
ca15 <- rep(cater15, length.out = length(namez15))

ratingz15 <- ratings2[[7]]
    if (length(ratingz15) > length(namez15)) {
    ratingz15 <- tail(ratingz15, length(namez15)) 
    } else if (length(ratingz15) < length(namez15)) {
    ratingz15 <- c(ratingz15, rep(NA, length(namez15) - length(ratingz15)))
    }
```

```{r}
skincare7 <- data.frame(Category = ca15,
                     Product_number = producto15,
                      Name_of_Product = produc15,
                      Userame = namez15,
                       Rating = ratingz15,
                       Date = dates2[[7]],
                       Title_of_Review = title2[[7]],
                       Text_of_Review = text2[[7]],
                       stringsAsFactors = FALSE
                       )
head(skincare7, 50)
```

```{r}
nama16 <- names2b[[1]]
namez16 <- nama16[!grepl("ELEMIS Superfood Midnight Facial", nama16, ignore.case = TRUE)]
namez16 <- namez16[-(1:2)]
producto16 <- productnumber2b[[1]]
producto16 <- rep(producto16, length.out = length(namez16))
produc16 <- nameofproduct2b[[1]]
produc16 <- rep(produc16, length.out = length(namez16))
cater16 <- category2b[[2]]
ca16 <- rep(cater16, length.out = length(namez16))

ratingz16 <- ratings2b[[1]]
    if (length(ratingz16) > length(namez16)) {
    ratingz16 <- tail(ratingz16, length(namez16)) 
    } else if (length(ratingz16) < length(namez16)) {
    ratingz16<- c(ratingz16, rep(NA, length(namez16) - length(ratingz16)))
    }
```

```{r}
skincare8 <- data.frame(Category = ca16,
                     Product_number = producto16,
                      Name_of_Product = produc16,
                      Userame = namez16,
                       Rating = ratingz16,
                       Date = dates2b[[1]],
                       Title_of_Review = title2b[[1]],
                       Text_of_Review = text2b[[1]],
                       stringsAsFactors = FALSE
                       )
head(skincare8, 50)
```
```{r}
names2b[[1]]
```


```{r}
nama17 <- names2b[[2]]
namez17 <- nama17[!grepl("amazing skincare products for youthful skin", nama17, ignore.case = TRUE)]
namez17 <- namez17[-(1:2)]
producto17 <- productnumber2b[[2]]
producto17 <- rep(producto17, length.out = length(namez17))
produc17 <- nameofproduct2b[[2]]
produc17 <- rep(produc17, length.out = length(namez17))
cater17 <- category2b[[2]]
ca17 <- rep(cater17, length.out = length(namez17))

ratingz17 <- ratings2b[[1]]
    if (length(ratingz17) > length(namez17)) {
    ratingz17 <- tail(ratingz17, length(namez17)) 
    } else if (length(ratingz17) < length(namez17)) {
    ratingz17<- c(ratingz17, rep(NA, length(namez17) - length(ratingz17)))
    }
```

```{r}
skincare9 <- data.frame(Category = ca17,
                     Product_number = producto17,
                      Name_of_Product = produc17,
                      Userame = namez17,
                       Rating = ratingz17,
                       Date = dates2b[[2]],
                       Title_of_Review = title2b[[2]],
                       Text_of_Review = text2b[[2]],
                       stringsAsFactors = FALSE
                       )
head(skincare9, 50)
```

```{r}
names2b[[2]]
```


```{r}
nama18 <- names2b[[3]]
namez18 <- nama18[!grepl("This wrapping mask", nama18, ignore.case = TRUE)]
namez18 <- namez18[-(1:2)]
producto18 <- productnumber2b[[3]]
producto18 <- rep(producto18, length.out = length(namez18))
produc18 <- nameofproduct2b[[3]]
produc18 <- rep(produc18, length.out = length(namez18))
cater18 <- category2b[[2]]
ca18 <- rep(cater18, length.out = length(namez18))

ratingz18 <- ratings2b[[1]]
    if (length(ratingz18) > length(namez18)) {
    ratingz18 <- tail(ratingz18, length(namez18)) 
    } else if (length(ratingz18) < length(namez18)) {
    ratingz18 <- c(ratingz18, rep(NA, length(namez18) - length(ratingz18)))
    }
```

```{r}
skincare10 <- data.frame(Category = ca18,
                     Product_number = producto18,
                      Name_of_Product = produc18,
                      Userame = namez18,
                       Rating = ratingz18,
                       Date = dates2b[[3]],
                       Title_of_Review = title2b[[3]],
                       Text_of_Review = text2b[[3]],
                       stringsAsFactors = FALSE
                       )
head(skincare10, 50)
```

```{r}
urls3 <- c('https://www.amazon.com/Marc-Jacobs-Daisy-Toilette-Spray-125ml/dp/B004IZJ2QG/ref=sr_1_6?crid=1AUIDZUV2WY9G&dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg6A9xRBgFFjFzBDUFtlOPDMsflk7n8Rx-OE4e0yBQHOHIALC2MXeIg6Q5U0i2SSEGg.2YmbwUyFAF_gQ74ROHQ8Ff1T_CopzzxfMDTfMDGgG3w&dib_tag=se&keywords=perfume&qid=1733542671&sprefix=perfume%2Caps%2C900&sr=8-6&th=1', 'https://www.amazon.com/Ralph-Lauren-Women-Toilette-Natural/dp/B000C1W3OS/ref=sr_1_7?crid=1AUIDZUV2WY9G&dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg6A9xRBgFFjFzBDUFtlOPDMsflk7n8Rx-OE4e0yBQHOHIALC2MXeIg6Q5U0i2SSEGg.2YmbwUyFAF_gQ74ROHQ8Ff1T_CopzzxfMDTfMDGgG3w&dib_tag=se&keywords=perfume&qid=1733542671&sprefix=perfume%2Caps%2C900&sr=8-7&th=1', 'https://www.amazon.com/Lanc%C3%B4me-Belle-Parfum-Spray-Ounce/dp/B00I7PK3GQ/ref=sr_1_9?dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg5OsG1P8e1oaDG88dxC3PyZ8bj04kyfGKSvkAGlavOtYo6JEKSabHMx4hy2xohySyg.dHr3Qq6OXXHMtQZNJGHvNiiMj5zYiVP5U4wLNjPIwfg&dib_tag=se&keywords=perfume&qid=1733545339&sr=8-9&th=1', 'https://www.amazon.com/Victorias-Secret-Fragrance-Mist-Vanilla/dp/B07JRG42D9/ref=sr_1_10?dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg5OsG1P8e1oaDG88dxC3PyZ8bj04kyfGKSvkAGlavOtYo6JEKSabHMx4hy2xohySyg.dHr3Qq6OXXHMtQZNJGHvNiiMj5zYiVP5U4wLNjPIwfg&dib_tag=se&keywords=perfume&qid=1733545339&sr=8-10&th=1', 'https://www.amazon.com/Victorias-Secret-Tease-Parfum-Spray/dp/B07GD5XVM1/ref=sr_1_17?dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg5OsG1P8e1oaDG88dxC3PyZ8bj04kyfGKSvkAGlavOtYo6JEKSabHMx4hy2xohySyg.dHr3Qq6OXXHMtQZNJGHvNiiMj5zYiVP5U4wLNjPIwfg&dib_tag=se&keywords=perfume&qid=1733545339&sr=8-17', 'https://www.amazon.com/Marc-Jacobs-Perfect-Parfum-Spray/dp/B08GKZ1233/ref=sr_1_18?dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg5OsG1P8e1oaDG88dxC3PyZ8bj04kyfGKSvkAGlavOtYo6JEKSabHMx4hy2xohySyg.dHr3Qq6OXXHMtQZNJGHvNiiMj5zYiVP5U4wLNjPIwfg&dib_tag=se&keywords=perfume&qid=1733545339&sr=8-18&th=1', 'https://www.amazon.com/Gucci-Bloom-Women-Parfum-Spray/dp/B074W8WQ3J/ref=sr_1_23?dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg5OsG1P8e1oaDG88dxC3PyZ8bj04kyfGKSvkAGlavOtYo6JEKSabHMx4hy2xohySyg.dHr3Qq6OXXHMtQZNJGHvNiiMj5zYiVP5U4wLNjPIwfg&dib_tag=se&keywords=perfume&qid=1733545339&sr=8-23&th=1')

nameofproduct3 <- vector("list", length(urls3))
names3 <- vector("list", length(urls3))
ratings3 <- vector("list", length(urls3))
dates3 <- vector("list", length(urls3))
title3 <- vector("list", length(urls3))
text3 <- vector("list", length(urls3))
n3 <- vector("list", length(urls3))
```

```{r}
df <- list()

for (i in seq_along(urls3)) {
    session3 <- bow(urls3[i], user_agent = "Educational")
    webpage3 <- scrape(session3)
  
    
    nam3 <- webpage3 %>% html_nodes(".a-profile-name") %>% html_text()
    nam3 <- nam3[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam3, ignore.case = TRUE)]
    nam3 <- nam3[nam3 != ""]
    n3[[i]] <- nam3
    name3 <- c() 
    non_amazon_seen3 <- FALSE  
    for (na3 in nam3) {
      if (na3 == "Amazon Customer") {

        if (non_amazon_seen3) {
          name3 <- c(name3, na3)
        }
      } else {
        name3 <- c(name3, na3)
        non_amazon_seen3 <- TRUE
        }
    }
    name3 <- name3[!duplicated(name3) | name3 == "Amazon Customer"]
    names3[[i]] <- name3
    
        nameofproduct3[[i]] <-  webpage3 %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct3[[i]] <- rep(nameofproduct3[[i]], length.out = length(names3[[i]]))
    
    rate3 <- webpage3 %>% html_nodes(".a-icon-alt") %>% html_text()
    rati3 <- rate3[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate3, ignore.case = TRUE)]
    rat3 <- gsub(" out of 5 stars", "", rati3)
    rats3 <- rat3
    if (length(rats3) > length(name3)) {
    rats3 <- tail(rats3, length(name3)) 
    } else if (length(rats3) < length(name3)) {
    rats3 <- c(rats3, rep(NA, length(name3) - length(rats3)))
    }

    ratings3[[i]] <- rats3
    
    dat3 <- webpage3 %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date3 <- gsub("Reviewed.*on ", "", dat3)
    dates3[[i]] <- date3

    titl3 <- webpage3 %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit3 <- gsub("Reviewed.*on ", "", titl3)
    ti3 <- gsub(".*stars\\s*", "", tit3)
    t3 <- gsub("\\s+", " ", ti3)
    title3[[i]] <- t3

    tex3 <- webpage3 %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te3 <- gsub("\\n", " ", tex3)
    t3 <- gsub("\\s+", " ", te3)
    text3[[i]] <- trimws(t3)
}
```

```{r}
cate3 <- c("Category 1: WATCH", "Category 2: SKINCARE", "Category 3: PERFUME", "Category 4", "Category 5")
category3 <- vector("list", length(cate3))
for (i in seq_along(cate3)) {
    category3[[i]] <- cate3[i]
}
```

```{r}
for (i in seq_along(cate3)) {
    category3[[i]] <- rep(category3[[i]], length.out = length(names3[[i]]))
}
```

```{r}
productnumbe3 <- c("Product 1", "Product 2", "Product 3", "Product 4", "Product 5", "Product 6", "Product 7", "Product 8", "Product 9", "Product 10")
productnumber3 <- vector("list", length(productnumbe3))
for (i in seq_along(productnumbe3)) {
    productnumber3[[i]] <- productnumbe3[i]
}
for (i in seq_along(urls3)) {
    productnumber3[[i]] <- rep(productnumber3[[i]], length.out = length(names3[[i]]))
}
```

```{r}
urls3b <- c('https://www.amazon.com/Victorias-Secret-Tease-Fragrance-8-4oz/dp/B09V1QM8VR/ref=sr_1_46?dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg5OsG1P8e1oaDG88dxC3PyZ8bj04kyfGKSvkAGlavOtYo6JEKSabHMx4hy2xohySyg.dHr3Qq6OXXHMtQZNJGHvNiiMj5zYiVP5U4wLNjPIwfg&dib_tag=se&keywords=perfume&qid=1733545339&sr=8-46&th=1', 'https://www.amazon.com/Victorias-Secret-Tease-3-4-Ounce/dp/B07GT42VY6/ref=sr_1_30?dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg5OsG1P8e1oaDG88dxC3PyZ8bj04kyfGKSvkAGlavOtYo6JEKSabHMx4hy2xohySyg.dHr3Qq6OXXHMtQZNJGHvNiiMj5zYiVP5U4wLNjPIwfg&dib_tag=se&keywords=perfume&qid=1733545339&sr=8-30&th=1', 'https://www.amazon.com/Mugler-Angel-Bergamot-Patchouli-Fragrance/dp/B0CW7NVYFD/ref=sr_1_32?dib=eyJ2IjoiMSJ9.zWSRq7La67uNUJ9gL9A3X8cjkozC7JPzdaWlWc65muYgm_5TLkkjU6AA6hkMa3Nx3Qb5OtzewOVDM72ZfhxfpeLloinK_IT50ckn8Gtohj70pGVQhMN52G2m5If0VLGukNT_LFAxt2yiBaTtP1dDQ8EAXmMj6mOla1fjaH7ddOZZHEth4isAJqitoY-5zBs8ZTiVuK2aWGC9QeAHlIfrVhPJ16tUrFHnpvSZ517Odg5OsG1P8e1oaDG88dxC3PyZ8bj04kyfGKSvkAGlavOtYo6JEKSabHMx4hy2xohySyg.dHr3Qq6OXXHMtQZNJGHvNiiMj5zYiVP5U4wLNjPIwfg&dib_tag=se&keywords=perfume&qid=1733545339&sr=8-32&th=1')
nameofproduct3b <- vector("list", length(urls3b))
names3b <- vector("list", length(urls3b))
ratings3b <- vector("list", length(urls3b))
dates3b <- vector("list", length(urls3b))
title3b <- vector("list", length(urls3b))
text3b <- vector("list", length(urls3b))
n3b <- vector("list", length(urls3b))
```

```{r}
df <- list()

for (i in seq_along(urls3b)) {
    session3b <- bow(urls3b[i], user_agent = "Educational")
    webpage3b <- scrape(session3b)
  
    
    nam3b <- webpage3b %>% html_nodes(".a-profile-name") %>% html_text()
    nam3b <- nam3b[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam3b, ignore.case = TRUE)]
    nam3b <- nam3b[nam3b != ""]
    n3b[[i]] <- nam3b
    name3b <- c() 
    non_amazon_seen3b <- FALSE  
    for (na3b in nam3b) {
      if (na3b == "Amazon Customer") {

        if (non_amazon_seen3b) {
          name3b <- c(name3b, na3b)
        }
      } else {
        name3b <- c(name3b, na3b)
        non_amazon_seen3b <- TRUE
        }
    }
    name3b <- name3b[!duplicated(name3b) | name3b == "Amazon Customer"]
    names3b[[i]] <- name3b
    
        nameofproduct3b[[i]] <-  webpage3b %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct3b[[i]] <- rep(nameofproduct3b[[i]], length.out = length(names3b[[i]]))
    
    rate3b <- webpage3b %>% html_nodes(".a-icon-alt") %>% html_text()
    rati3b <- rate3b[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate3b, ignore.case = TRUE)]
    rat3b <- gsub(" out of 5 stars", "", rati3b)
    rats3b <- rat3b
    if (length(rats3b) > length(name3b)) {
    rats3b <- tail(rats3b, length(name3b)) 
    } else if (length(rats3b) < length(name3b)) {
    rats3b <- c(rats3b, rep(NA, length(name3b) - length(rats3b)))
    }
    ratings3b[[i]] <- rats3b
    dat3b <- webpage3b %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date3b <- gsub("Reviewed.*on ", "", dat3b)
    dates3b[[i]] <- date3b

    titl3b <- webpage3b %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit3b <- gsub("Reviewed.*on ", "", titl3b)
    ti3b <- gsub(".*stars\\s*", "", tit3b)
    t3b <- gsub("\\s+", " ", ti3b)
    title3b[[i]] <- t3b

    tex3b <- webpage3b %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te3b <- gsub("\\n", " ", tex3b)
    t3b <- gsub("\\s+", " ", te3b)
    text3b[[i]] <- trimws(t3b)
}
```

```{r}
cate3b <- c("Category 1: WATCH", "Category 2: SKINCARE", "Category 3: PERFUME", "Category 4:", "Category 5:")
category3b <- vector("list", length(cate3b))
for (i in seq_along(cate3b)) {
    category3b[[i]] <- cate3b[i]
}
```

```{r}
for (i in seq_along(urls3b)) {
    category3b[[i]] <- rep(category3b[[i]], length.out = length(names3b[[i]]))
}
```

```{r}
productnumbe3b <- c("Product 8", "Product 9", "Product 10")
productnumber3b <- vector("list", length(productnumbe3b))
for (i in seq_along(productnumbe3b)) {
    productnumber3b[[i]] <- productnumbe3b[i]
}
```

```{r}
for (i in seq_along(productnumber3b)) {
    productnumber3b[[i]] <- rep(productnumber3b[[i]], length.out = length(names3b[[i]]))
}
```

```{r}
names3
names3b
```

```{r}
nama31 <- names3[[1]]
namez31 <- nama31[!grepl("What You Should", nama31, ignore.case = TRUE)]
namez31 <- namez31[-(1:2)]
producto31 <- productnumber3[[1]]
producto31 <- rep(producto31, length.out = length(namez31))
produc31 <- nameofproduct3[[1]]
produc31 <- rep(produc31, length.out = length(namez31))
cater31 <- category3[[3]]
ca31 <- rep(cater31, length.out = length(namez31))

ratingz31 <- ratings3[[1]]
    if (length(ratingz31) > length(namez31)) {
    ratingz31 <- tail(ratingz31, length(namez31)) 
    } else if (length(ratingz31) < length(namez31)) {
    ratingz31 <- c(ratingz31, rep(NA, length(namez31) - length(ratingz31)))
    }
```

```{r}
perfume1 <- data.frame(Category = ca31,
                     Product_number = producto31,
                      Name_of_Product = produc31,
                      Userame = namez31,
                       Rating = ratingz31,
                       Date = dates3[[1]],
                       Title_of_Review = title3[[1]],
                       Text_of_Review = text3[[1]],
                       stringsAsFactors = FALSE
                       )
head(perfume1, 50)
```

```{r}
nama32 <- names3[[2]]
namez32 <- nama32[!grepl("Is Ralph by Ralph Lauren a Good Fit For You?", nama32, ignore.case = TRUE)]
namez32 <- namez32[-(1:2)]
producto32 <- productnumber3[[2]]
producto32 <- rep(producto32, length.out = length(namez32))
produc32 <- nameofproduct3[[2]]
produc32 <- rep(produc32, length.out = length(namez32))
cater32 <- category3[[3]]
ca32 <- rep(cater32, length.out = length(namez32))

ratingz32 <- ratings3[[2]]
    if (length(ratingz32) > length(namez32)) {
    ratingz32 <- tail(ratingz32, length(namez32)) 
    } else if (length(ratingz32) < length(namez32)) {
    ratingz32 <- c(ratingz32, rep(NA, length(namez32) - length(ratingz32)))
    }
```

```{r}
perfume2 <- data.frame(Category = ca32,
                     Product_number = producto32,
                      Name_of_Product = produc32,
                      Userame = namez32,
                       Rating = ratingz32,
                       Date = dates3[[2]],
                       Title_of_Review = title3[[2]],
                       Text_of_Review = text3[[2]],
                       stringsAsFactors = FALSE
                       )
head(perfume2, 50)
```

```{r}
names3[[2]]
```


```{r}
nama33 <- names3[[3]]
namez33 <- nama33[!grepl("La Vie Est", nama33, ignore.case = TRUE)]
namez33 <- namez33[-(1:2)]
producto33 <- productnumber3[[3]]
producto33 <- rep(producto33, length.out = length(namez33))
produc33 <- nameofproduct3[[3]]
produc33 <- rep(produc33, length.out = length(namez33))
cater33 <- category3[[3]]
ca33 <- rep(cater33, length.out = length(namez33))

ratingz33 <- ratings3[[3]]
    if (length(ratingz33) > length(namez33)) {
    ratingz33 <- tail(ratingz33, length(namez33)) 
    } else if (length(ratingz33) < length(namez33)) {
    ratingz33<- c(ratingz33, rep(NA, length(namez33) - length(ratingz33)))
    }
```

```{r}
perfume3 <- data.frame(Category = ca33,
                     Product_number = producto33,
                      Name_of_Product = produc33,
                      Userame = namez33,
                       Rating = ratingz33,
                       Date = dates3[[3]],
                       Title_of_Review = title3[[3]],
                       Text_of_Review = text3[[3]],
                       stringsAsFactors = FALSE
                       )
head(perfume3, 50)
```

```{r}
nama34 <- names3[[4]]
namez34 <- nama34[!grepl("Victoria's Secret Bare", nama34, ignore.case = TRUE)]
namez34 <- namez34[-(1:2)]
producto34 <- productnumber3[[4]]
producto34 <- rep(producto34, length.out = length(namez34))
produc34 <- nameofproduct3[[4]]
produc34 <- rep(produc34, length.out = length(namez34))
cater34 <- category3[[3]]
ca34 <- rep(cater34, length.out = length(namez34))

ratingz34 <- ratings3[[4]]
    if (length(ratingz34) > length(namez34)) {
    ratingz34 <- tail(ratingz34, length(namez34)) 
    } else if (length(ratingz34) < length(namez34)) {
    ratingz34<- c(ratingz34, rep(NA, length(namez34) - length(ratingz34)))
    }
```

```{r}
perfume4 <- data.frame(Category = ca34,
                     Product_number = producto34,
                      Name_of_Product = produc34,
                      Userame = namez34,
                       Rating = ratingz34,
                       Date = dates3[[4]],
                       Title_of_Review = title3[[4]],
                       Text_of_Review = text3[[4]],
                       stringsAsFactors = FALSE
                       )
head(perfume4, 50)
```

```{r}
nama35 <- names3[[5]]
namez35 <- nama35[!grepl("Bombshell Seduction Video", nama35, ignore.case = TRUE)]
namez35 <- namez35[-(1:2)]
producto35 <- productnumber3[[5]]
producto35 <- rep(producto35, length.out = length(namez35))
produc35 <- nameofproduct3[[5]]
produc35 <- rep(produc35, length.out = length(namez35))
cater35 <- category3[[3]]
ca35 <- rep(cater35, length.out = length(namez35))

ratingz35 <- ratings3[[5]]
    if (length(ratingz35) > length(namez35)) {
    ratingz35 <- tail(ratingz35, length(namez35)) 
    } else if (length(ratingz3) < length(namez3)) {
    ratingz35 <- c(ratingz35, rep(NA, length(namez35) - length(ratingz35)))
    }
```

```{r}
perfume5 <- data.frame(Category = ca35,
                     Product_number = producto35,
                      Name_of_Product = produc35,
                      Userame = namez35,
                       Rating = ratingz35,
                       Date = dates3[[5]],
                       Title_of_Review = title3[[5]],
                       Text_of_Review = text3[[5]],
                       stringsAsFactors = FALSE
                       )
head(perfume5, 50)
```

```{r}
nama36 <- names3[[6]]
namez36 <- nama36[!grepl("Honest Review Of", nama36, ignore.case = TRUE)]
namez36 <- namez36[-(1:2)]
producto36 <- productnumber3[[6]]
producto36 <- rep(producto36, length.out = length(namez36))
produc36 <- nameofproduct3[[6]]
produc36 <- rep(produc36, length.out = length(namez36))
cater36 <- category3[[3]]
ca36 <- rep(cater36, length.out = length(namez36))

ratingz36 <- ratings3[[6]]
    if (length(ratingz36) > length(namez36)) {
    ratingz36 <- tail(ratingz36, length(namez36)) 
    } else if (length(ratingz36) < length(namez36)) {
    ratingz36 <- c(ratingz36, rep(NA, length(namez36) - length(ratingz36)))
    }
```

```{r}
perfume6 <- data.frame(Category = ca36,
                     Product_number = producto36,
                      Name_of_Product = produc36,
                      Userame = namez36,
                       Rating = ratingz36,
                       Date = dates3[[6]],
                       Title_of_Review = title3[[6]],
                       Text_of_Review = text3[[6]],
                       stringsAsFactors = FALSE
                       )
head(perfume6, 50)
```

```{r}
nama37 <- names3[[7]]
namez37 <- nama37[!grepl("The ReCap: Gucci", nama37, ignore.case = TRUE)]
namez37 <- namez37[-(1:2)]
producto37 <- productnumber3[[7]]
producto37 <- rep(producto37, length.out = length(namez37))
produc37 <- nameofproduct3[[7]]
produc37 <- rep(produc37, length.out = length(namez37))
cater37 <- category3[[3]]
ca37 <- rep(cater37, length.out = length(namez37))

ratingz37 <- ratings3[[7]]
    if (length(ratingz37) > length(namez37)) {
    ratingz37 <- tail(ratingz37, length(namez37)) 
    } else if (length(ratingz3) < length(namez3)) {
    ratingz37 <- c(ratingz37, rep(NA, length(namez37) - length(ratingz37)))
    }
```

```{r}
perfume7 <- data.frame(Category = ca37,
                     Product_number = producto37,
                      Name_of_Product = produc37,
                      Userame = namez37,
                       Rating = ratingz37,
                       Date = dates3[[7]],
                       Title_of_Review = title3[[7]],
                       Text_of_Review = text3[[7]],
                       stringsAsFactors = FALSE
                       )
head(perfume7, 50)
```

```{r}
nama38 <- names3b[[1]]
namez38 <- nama38[!grepl("Victoria's Secret Tease", nama38, ignore.case = TRUE)]
namez38 <- namez38[-(1:2)]
producto38 <- productnumber3b[[1]]
producto38 <- rep(producto38, length.out = length(namez38))
produc38 <- nameofproduct3b[[1]]
produc38 <- rep(produc38, length.out = length(namez38))
cater38 <- category3b[[3]]
ca38 <- rep(cater38, length.out = length(namez38))

ratingz38 <- ratings3b[[1]]
    if (length(ratingz38) > length(namez38)) {
    ratingz38 <- tail(ratingz38, length(namez38)) 
    } else if (length(ratingz38) < length(namez38)) {
    ratingz38<- c(ratingz38, rep(NA, length(namez38) - length(ratingz38)))
    }
```

```{r}
perfume8 <- data.frame(Category = ca38,
                     Product_number = producto38,
                      Name_of_Product = produc38,
                      Userame = namez38,
                       Rating = ratingz38,
                       Date = dates3b[[1]],
                       Title_of_Review = title3b[[1]],
                       Text_of_Review = text3b[[1]],
                       stringsAsFactors = FALSE
                       )
head(perfume8, 50)
```

```{r}
nama39 <- names3b[[2]]
namez39 <- nama39[!grepl("Victoria's Secret Tease", nama39, ignore.case = TRUE)]
namez39 <- namez39[-(1:2)]
producto39 <- productnumber3b[[2]]
producto39 <- rep(producto39, length.out = length(namez39))
produc39 <- nameofproduct3b[[2]]
produc39 <- rep(produc39, length.out = length(namez39))
cater39 <- category3b[[3]]
ca39 <- rep(cater39, length.out = length(namez39))

ratingz39 <- ratings3b[[2]]
    if (length(ratingz39) > length(namez39)) {
    ratingz39 <- tail(ratingz39, length(namez39)) 
    } else if (length(ratingz39) < length(namez39)) {
    ratingz39 <- c(ratingz39, rep(NA, length(namez39) - length(ratingz39)))
    }
```

```{r}
perfume9 <- data.frame(Category = ca39,
                     Product_number = producto39,
                      Name_of_Product = produc39,
                      Userame = namez39,
                       Rating = ratingz39,
                       Date = dates3b[[2]],
                       Title_of_Review = title3b[[2]],
                       Text_of_Review = text3b[[2]],
                       stringsAsFactors = FALSE
                       )
head(perfume9, 50)
```

```{r}
nama310 <- names3b[[3]]
namez310 <- nama310[!grepl("MUGLER Angel Eau", nama310, ignore.case = TRUE)]
namez310 <- namez310[-(1:2)]
producto310 <- productnumber3b[[3]]
producto310 <- rep(producto310, length.out = length(namez310))
produc310 <- nameofproduct3b[[3]]
produc310 <- rep(produc310, length.out = length(namez310))
cater310 <- category3b[[3]]
ca310 <- rep(cater310, length.out = length(namez310))

ratingz310 <- ratings3b[[3]]
    if (length(ratingz310) > length(namez310)) {
    ratingz310 <- tail(ratingz310, length(namez310)) 
    } else if (length(ratingz310) < length(namez310)) {
    ratingz310 <- c(ratingz310, rep(NA, length(namez310) - length(ratingz310)))
    }
```

```{r}
perfume10 <- data.frame(Category = ca310,
                     Product_number = producto310,
                      Name_of_Product = produc310,
                      Userame = namez310,
                       Rating = ratingz310,
                       Date = dates3b[[3]],
                       Title_of_Review = title3b[[3]],
                       Text_of_Review = text3b[[3]],
                       stringsAsFactors = FALSE
                       )
head(perfume10, 50)
```

# category 4

```{r}
urls4 <- c('https://www.amazon.com/Amazon-Essentials-Womens-Belice-Ballet/dp/B07PT7LL7J/ref=sr_1_1_ffob_sspa?crid=2XIYNMHBPWQZ6&dib=eyJ2IjoiMSJ9.0F4CxSPN7mwJEPB3HcMU5ztrZ7w4wiqfJUuSdFJM-J7hLZSSVj8zcO0U-23SznCSoGu4fB8yoVK-6qJGWcNg9BNznPf5pJHbfQ-2sAL6Lm0-4gmhYxZOH9loWI6xOeBceiilonDUePkLYW5-N9Sihh-jcX8CLlsv488pZKohrlc8L8eTpA59n2gUX0leoxiKrJ1XwNDq6RtFMHdbznU3Thp8QLZPQbbGOodhV4D3av3G2wDq15oNRc2p8mVNgIMD2yPcKIRv6HBYHjJlsTvs8eGKxm_be4x0jCDHhQyTj2M.VAV2gTthgGzQn8875PKnRuEBmgQdg-pef8VTWsr59UM&dib_tag=se&keywords=shoes&qid=1733536085&sprefix=shoes%2Caps%2C615&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&psc=1', 'https://www.amazon.com/Under-Armour-Charged-Assert-Running/dp/B09XBWCQF1/ref=sr_1_5?crid=204X61UH6HXML&dib=eyJ2IjoiMSJ9.-gRsUYr102Q9bQ4t7WGzXQ9tK3qOE2qLtiezCdMO8-_hLZSSVj8zcO0U-23SznCSj0qQn0gqjydUQpf-0_31cDtWNYlq3uFhSUq3GWp-UJYLml2R1btwtoi6JADBSXM0hfeYOVQRovzwXM7E19WS0c7LNIYgdq7pIO0H1P1P6D1eS5rzahgPB21e628Pfl3mY0OF0RMFXMepFZWomkNDjXb_y9eJSkCwcyyWYXyQ961AnyMUrvOo3QCyMoTzI2qLYQwkTdANSQUoptG7mUYwVxx50XCGmUAnp6Q3Urkcvh0.C1NyXqfwZybQJOMBsCJDJNzynCaUQcGJO3bCw9UYfig&dib_tag=se&keywords=shoes&qid=1733573548&sprefix=shoes%2Caps%2C824&sr=8-5&th=1', 'https://www.amazon.com/dp/B09C8HMV5S/ref=sspa_dk_detail_4?pd_rd_i=B09C8HMV5S&pd_rd_w=aInFo&content-id=amzn1.sym.386c274b-4bfe-4421-9052-a1a56db557ab&pf_rd_p=386c274b-4bfe-4421-9052-a1a56db557ab&pf_rd_r=B066BV81K12X1MJ45H91&pd_rd_wg=fjvmI&pd_rd_r=21930c5f-b723-4b42-bc72-2df2e590b232&s=shoes&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&th=1&psc=1', 'https://www.amazon.com/dp/B0BZYRJG1K/ref=sspa_dk_detail_2?pd_rd_i=B0BZYRJG1K&pd_rd_w=YXtGt&content-id=amzn1.sym.386c274b-4bfe-4421-9052-a1a56db557ab&pf_rd_p=386c274b-4bfe-4421-9052-a1a56db557ab&pf_rd_r=G3154DE3CVC6VADAABNY&pd_rd_wg=dRLJm&pd_rd_r=63c99075-cc5e-4fca-b3a2-16b7e4f28551&s=shoes&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&th=1&psc=1', 'https://www.amazon.com/dp/B0CJT749XG/ref=sspa_dk_detail_0?pd_rd_i=B0CJT749XG&pd_rd_w=IegKC&content-id=amzn1.sym.8c2f9165-8e93-42a1-8313-73d3809141a2&pf_rd_p=8c2f9165-8e93-42a1-8313-73d3809141a2&pf_rd_r=SZ9N8BVMJYK1CPQG4SW0&pd_rd_wg=eveGQ&pd_rd_r=b5f80106-681d-45b6-b11a-f2317a2b55e4&s=shoes&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&th=1&psc=1')

nameofproduct4 <-vector("list", length(urls4))
names4 <- vector("list", length(urls4))
ratings4 <- vector("list", length(urls4))
dates4 <- vector("list", length(urls4))
title4 <- vector("list", length(urls4))
text4 <- vector("list", length(urls4))
n4 <- vector("list", length(urls4))
```


```{r}
df <- list()

for (i in seq_along(urls4)) {
    session <- bow(urls4[i], user_agent = "Educational")

  webpage4 <- scrape(session)

  nam4 <-webpage4 %>% html_nodes(".a-profile-name") %>% html_text()
  nam4 <- nam4[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam4, ignore.case = TRUE)]
    nam4 <- nam4[nam4 != ""]
    n4[[i]] <- nam4
    name4 <- c() 
    non_amazon_seen4 <- FALSE  
    for (na4 in nam4) {
      if (na4 == "Amazon Customer") {

        if (non_amazon_seen4) {
          name4 <- c(name4, na4)
        }
      } else {
        name4 <- c(name4, na4)
        non_amazon_seen4 <- TRUE
        }
    }
    name4 <- name4[!duplicated(name4) | name4 == "Amazon Customer"]
    names4[[i]] <- name4
    
        nameofproduct4[[i]] <-  webpage4 %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct4[[i]] <- rep(nameofproduct4[[i]], length.out = length(names4[[i]]))
    
    rate4 <- webpage4 %>% html_nodes(".a-icon-alt") %>% html_text()
    rati4 <- rate4[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate4, ignore.case = TRUE)]
    rat4 <- gsub(" out of 5 stars", "", rati4)
    rats4 <- rat4
    if (length(rats4) > length(name4)) {
    rats4 <- tail(rats4, length(name4)) 
    } else if (length(rats4) < length(name4)) {
    rats4 <- c(rats4, rep(NA, length(name4) - length(rats4)))
    }

    ratings4[[i]] <- rats4
    
    dat4 <- webpage4 %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date4 <- gsub("Reviewed.*on ", "", dat4)
    dates4[[i]] <- date4

    titl4 <- webpage4 %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit4 <- gsub("Reviewed.*on ", "", titl4)
    ti4 <- gsub(".*stars\\s*", "", tit4)
    t4 <- gsub("\\s+", " ", ti4)
    title4[[i]] <- t4

    tex4 <- webpage4 %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te4 <- gsub("\\n", " ", tex4)
    t4 <- gsub("\\s+", " ", te4)
    text4[[i]] <- trimws(t4)
}
```


```{r}
cate4 <- c("Category 1: WATCH", "Category 2", "Category 3", "Category 4: SHOES", "Category 5")
category4 <- vector("list", length(cate4))
for (i in seq_along(cate4)) {
    category4[[i]] <- cate4[i]
}
```


```{r}
for (i in seq_along(urls4)) {
    category4[[i]] <- rep(category4[[i]], length.out = length(names4[[i]]))
}
```


```{r}
productnumbe4 <- c("Product 1", "Product 2", "Product 3", "Product 4", "Product 5")
productnumber4 <- vector("list", length(productnumbe4))
for (i in seq_along(productnumbe4)) {
    productnumber4[[i]] <- productnumbe4[i]
}
for (i in seq_along(urls4)) {
    productnumber4[[i]] <- rep(productnumber4[[i]], length.out = length(names4[[i]]))
}
```


```{r}
nama4 <- names4[[1]]
namez4 <- nama4[!grepl("360 Degree View", nama4, ignore.case = TRUE)]
namez4 <- unique(namez4)
namez4 <- namez4[-1]
producto4 <- productnumber4[[1]]
producto4 <- rep(producto4, length.out = length(namez4))
produc4 <- nameofproduct4[[1]]
produc4 <- rep(produc4, length.out = length(namez4))
cater4 <- category4[[4]]
ca4 <- rep(cater4, length.out = length(namez4))

ratingz4 <- ratings4[[1]]
    if (length(ratingz4) > length(namez4)) {
    ratingz4 <- tail(ratingz4, length(namez4)) 
    } else if (length(ratingz4) < length(namez4)) {
    ratingz4 <- c(ratingz4, rep(NA, length(namez4) - length(ratingz4)))
    }
```


```{r}
shoes1 <- data.frame(Category = ca4,
                     Product_number = producto4,
                      Name_of_Product = produc4,
                      Userame = namez4,
                       Rating = ratingz4,
                       Date = dates4[[1]],
                       Title_of_Review = title4[[1]],
                       Text_of_Review = text4[[1]],
                       stringsAsFactors = FALSE
                       )
head(shoes1, 50)
```


```{r}
namez4
```


```{r}
nama42 <- names4[[2]]
namez42 <- nama42[!grepl("Men's", nama42, ignore.case = TRUE)]
namez42 <- unique(namez42)
namez42 <- namez42[-(2:2)]
producto42 <- productnumber4[[2]]
producto42 <- rep(producto42, length.out = length(namez42))
produc42 <- nameofproduct4[[2]]
produc42 <- rep(produc42, length.out = length(namez42))
cater42 <- category4[[4]]
ca42 <- rep(cater42, length.out = length(namez42))

ratingz42 <- ratings4[[2]]
    if (length(ratingz42) > length(namez42)) {
    ratingz42 <- tail(ratingz42, length(namez42)) 
    } else if (length(ratingz42) < length(namez42)) {
    ratingz42 <- c(ratingz42, rep(NA, length(namez42) - length(ratingz42)))
    }
```


```{r}
shoes2 <- data.frame(Category = ca42,
                     Product_number = producto42,
                      Name_of_Product = produc42,
                      Userame = namez42,
                       Rating = ratingz42,
                       Date = dates4[[2]],
                       Title_of_Review = title4[[2]],
                       Text_of_Review = text4[[2]],
                       stringsAsFactors = FALSE
                       )
head(shoes2, 50)
```


```{r}
namez42
```


```{r}
nama43 <- names4[[3]]
namez43 <- nama43[!grepl("Square Toe Low Heel", nama43, ignore.case = TRUE)]
namez43 <- namez43[-(1:2)]
namez43 <- unique(namez43)
producto43 <- productnumber4[[3]]
producto43 <- rep(producto43, length.out = length(namez43))
produc43 <- nameofproduct4[[3]]
produc43 <- rep(produc43, length.out = length(namez43))
cater43 <- category4[[4]]
ca43 <- rep(cater43, length.out = length(namez43))

ratingz43 <- ratings4[[3]]
    if (length(ratingz43) > length(namez43)) {
    ratingz43 <- tail(ratingz43, length(namez43)) 
    } else if (length(ratingz43) < length(namez43)) {
    ratingz43 <- c(ratingz43, rep(NA, length(namez43) - length(ratingz43)))
    }
```


```{r}
shoes3 <- data.frame(Category = ca43,
                     Product_number = producto43,
                      Name_of_Product = produc43,
                      Userame = namez43,
                       Rating = ratingz43,
                       Date = dates4[[3]],
                       Title_of_Review = title4[[3]],
                       Text_of_Review = text4[[3]],
                       stringsAsFactors = FALSE
                       )
head(shoes3, 50)
```

```{r}
names4[[3]]
```
 
```{r}
nama44 <- names4[[4]]
namez44 <- nama44[!grepl("MAlexander", nama44, ignore.case = TRUE)]
namez44 <- namez44[-(1:2)]
namez44 <- unique(namez44)
producto44 <- productnumber4[[4]]
producto44 <- rep(producto44, length.out = length(namez44))
produc44 <- nameofproduct4[[4]]
produc44 <- rep(produc44, length.out = length(namez44))
cater44 <- category4[[4]]
ca44 <- rep(cater44, length.out = length(namez44))

ratingz44 <- ratings4[[4]]
    if (length(ratingz44) > length(namez44)) {
    ratingz44 <- tail(ratingz44, length(namez44)) 
    } else if (length(ratingz44) < length(namez44)) {
    ratingz44 <- c(ratingz44, rep(NA, length(namez44) - length(ratingz44)))
    }
```


```{r}
shoes4 <- data.frame(Category = ca44,
                     Product_number = producto44,
                      Name_of_Product = produc44,
                      Userame = namez44,
                       Rating = ratingz44,
                       Date = dates4[[4]],
                       Title_of_Review = title4[[4]],
                       Text_of_Review = text4[[4]],
                       stringsAsFactors = FALSE
                       )
head(shoes4, 50)
```
```{r}
names4[[4]]
```

```{r}
nama45 <- names4[[5]]
namez45 <- nama45[!grepl("Lockdown 7 Basketball Shoe", nama45, ignore.case = TRUE)]
namez45 <- namez45[-(1:2)]
namez45 <- unique(namez45)
producto45 <- productnumber4[[5]]
producto45 <- rep(producto45, length.out = length(namez45))
produc45 <- nameofproduct4[[5]]
produc45 <- rep(produc45, length.out = length(namez45))
cater45 <- category4[[4]]
ca45 <- rep(cater45, length.out = length(namez45))

ratingz45 <- ratings4[[5]]
    if (length(ratingz45) > length(namez45)) {
    ratingz45 <- tail(ratingz45, length(namez45)) 
    } else if (length(ratingz45) < length(namez45)) {
    ratingz45 <- c(ratingz45, rep(NA, length(namez45) - length(ratingz45)))
    }
```


```{r}
shoes5 <- data.frame(Category = ca45,
                     Product_number = producto45,
                      Name_of_Product = produc45,
                      Userame = namez45,
                       Rating = ratingz45,
                       Date = dates4[[5]],
                       Title_of_Review = title4[[5]],
                       Text_of_Review = text4[[5]],
                       stringsAsFactors = FALSE
                       )
head(shoes5, 50)
```

```{r}
names4[[5]]
```


```{r}
urls4b <- c('https://www.amazon.com/DREAM-PAIRS-Chunky-T-Strap-Wedding/dp/B0967LKZCL/ref=slsr_d_dpds_fsdp4star_fa_affordableprice_d_sccl_4_2/146-7533384-2764569?pd_rd_w=LjwYV&content-id=amzn1.sym.ad26ea41-1faa-4c86-921b-b7ed8438d88b&pf_rd_p=ad26ea41-1faa-4c86-921b-b7ed8438d88b&pf_rd_r=2VM2NWWC6YY3KZP67TM0&pd_rd_wg=oeuzV&pd_rd_r=3bd35d45-5167-4d7f-b852-140b941292fa&pd_rd_i=B0967LKZCL&th=1&psc=1', 'https://www.amazon.com/dp/B08SGWSG3V/ref=sspa_dk_detail_2?pd_rd_i=B08SGWSG3V&pd_rd_w=JTATJ&content-id=amzn1.sym.386c274b-4bfe-4421-9052-a1a56db557ab&pf_rd_p=386c274b-4bfe-4421-9052-a1a56db557ab&pf_rd_r=JR6806GVCNPGTF99XWCK&pd_rd_wg=etqEc&pd_rd_r=ff3fded5-329e-436d-9aae-21b6fd5a7b9b&s=shoes&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&th=1&psc=1', 'https://www.amazon.com/dp/B088TWBB44/ref=sspa_dk_detail_0?pd_rd_i=B088TWBB44&pd_rd_w=Vp9nA&content-id=amzn1.sym.2283fd66-e1b9-4348-a035-8043f03d31b8&pf_rd_p=2283fd66-e1b9-4348-a035-8043f03d31b8&pf_rd_r=Q19Q07JSN4JBTQDY7N8C&pd_rd_wg=1D2Cf&pd_rd_r=cfdaf3e1-d456-40a3-b2c3-2cef392eb0ba&s=shoes&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&th=1&psc=1', 'https://www.amazon.com/IGxx-Glitter-Flashing-Lace-up-Sneakers/dp/B0BB38521L/ref=sr_1_14_sspa?crid=2RN625LYMH856&dib=eyJ2IjoiMSJ9.bvTTeJ8AUdxV366f5uJefddsSpnLIuEaXEEzIWVrJnqz78Afw0pdJefQyMFJy4SZelgQNQtDwWLMNvTDdLqe1Xxb0LDJ60Ah3g5L5Yj0ULKaLFusI-ojYmrwZZjXn3-IZgFHRmfL2-JccKfR4HnhxkttwVQ3yCZanvCxNssaMGAQm24De_7Pg-KUph8TJ2TmiAcbMRRK6E_01qWZne_M59znGu_UPUTr0QHWz9WHfXfzsliz6ZNaWQWylGcjfIc-moCdLP6-_27gM9pdfFCgUN3Y4Fxd2dioY2odoJYMj-w.4m110X5uhjF2VK2OkQzxbDO98CAQBjiqhuKB01q7g50&dib_tag=se&keywords=shoes&qid=1733725512&sprefix=shoes%2Caps%2C634&sr=8-14-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&th=1&psc=1', 'https://www.amazon.com/dp/B0CWXMKQ69/ref=sspa_dk_detail_1?pd_rd_i=B0CWXMKQ69&pd_rd_w=Galp7&content-id=amzn1.sym.8c2f9165-8e93-42a1-8313-73d3809141a2&pf_rd_p=8c2f9165-8e93-42a1-8313-73d3809141a2&pf_rd_r=TNEPF9FGF4FSG0NN50CF&pd_rd_wg=lIQ1U&pd_rd_r=a2d7f5fe-b6ff-4f2b-a5d2-c45077c205ce&s=shoes&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&th=1&psc=1')

nameofproduct4b <-vector("list", length(urls4b))
names4b <- vector("list", length(urls4b))
ratings4b <- vector("list", length(urls4b))
dates4b <- vector("list", length(urls4b))
title4b <- vector("list", length(urls4b))
text4b <- vector("list", length(urls4b))
n4b <- vector("list", length(urls4b))
```


```{r}
df <- list()

for (i in seq_along(urls4b)) {
    session <- bow(urls4b[i], user_agent = "Educational")

  webpage4b <- scrape(session)

  nam4b <-webpage4b %>% html_nodes(".a-profile-name") %>% html_text()
  nam4b <- nam4b[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam4b, ignore.case = TRUE)]
    nam4b <- nam4b[nam4b != ""]
    n4b[[i]] <- nam4b
    name4b <- c() 
    non_amazon_seen4b <- FALSE  
    for (na4b in nam4b) {
      if (na4b == "Amazon Customer") {

        if (non_amazon_seen4b) {
          name4b <- c(name4b, na4b)
        }
      } else {
        name4b <- c(name4b, na4b)
        non_amazon_seen4b <- TRUE
        }
    }
    name4b <- name4b[!duplicated(name4b) | name4b == "Amazon Customer"]
    names4b[[i]] <- name4b
    
        nameofproduct4b[[i]] <-  webpage4b %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct4b[[i]] <- rep(nameofproduct4b[[i]], length.out = length(names4b[[i]]))
    
    rate4b <- webpage4b %>% html_nodes(".a-icon-alt") %>% html_text()
    rati4b <- rate4b[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate4b, ignore.case = TRUE)]
    rat4b <- gsub(" out of 5 stars", "", rati4b)
    rats4b <- rat4b
    if (length(rats4b) > length(name4b)) {
    rats4b <- tail(rats4b, length(name4b)) 
    } else if (length(rats4b) < length(name4b)) {
    rats4b <- c(rats4b, rep(NA, length(name4b) - length(rats4b)))
    }

    ratings4b[[i]] <- rats4b
    
    dat4b <- webpage4b %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date4b <- gsub("Reviewed.*on ", "", dat4b)
    dates4b[[i]] <- date4b

    titl4b <- webpage4b %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit4b <- gsub("Reviewed.*on ", "", titl4b)
    ti4b <- gsub(".*stars\\s*", "", tit4b)
    t4b <- gsub("\\s+", " ", ti4b)
    title4b[[i]] <- t4b

    tex4b <- webpage4b %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te4b <- gsub("\\n", " ", tex4b)
    t4b <- gsub("\\s+", " ", te4b)
    text4b[[i]] <- trimws(t4b)
}
```


```{r}
cate4b <- c("Category 1: WATCH", "Category 2", "Category 3", "Category 4: SHOES", "Category 5")
category4b <- vector("list", length(cate4b))
for (i in seq_along(cate4b)) {
    category4b[[i]] <- cate4b[i]
}
```


```{r}
for (i in seq_along(urls4b)) {
    category4b[[i]] <- rep(category4b[[i]], length.out = length(names4b[[i]]))
}
```


```{r}
productnumbe4b <- c("Product 6", "Product 7", "Product 8", "Product 9", "Product 10")
productnumber4b <- vector("list", length(productnumbe4b))
for (i in seq_along(productnumbe4b)) {
    productnumber4b[[i]] <- productnumbe4b[i]
}
for (i in seq_along(urls4b)) {
    productnumber4b[[i]] <- rep(productnumber4b[[i]], length.out = length(names4b[[i]]))
}
```


```{r}
nama4b <- names4b[[1]]
namez4b <- nama4b[!grepl("Amazon Customer", nama4b, ignore.case = TRUE)]
namez4b <- unique(namez4b)
namez4b <- namez4b[-1]
producto4b <- productnumber4b[[1]]
producto4b <- rep(producto4b, length.out = length(namez4b))
produc4b <- nameofproduct4b[[1]]
produc4b <- rep(produc4b, length.out = length(namez4b))
cater4b <- category4b[[4]]
ca4b <- rep(cater4b, length.out = length(namez4b))

ratingz4b <- ratings4b[[1]]
    if (length(ratingz4b) > length(namez4b)) {
    ratingz4b <- tail(ratingz4b, length(namez4b)) 
    } else if (length(ratingz4b) < length(namez4b)) {
    ratingz4b <- c(ratingz4b, rep(NA, length(namez4b) - length(ratingz4b)))
    }
```


```{r}
shoes6 <- data.frame(Category = ca4b,
                     Product_number = producto4b,
                      Name_of_Product = produc4b,
                      Userame = namez4b,
                       Rating = ratingz4b,
                       Date = dates4b[[1]],
                       Title_of_Review = title4b[[1]],
                       Text_of_Review = text4b[[1]],
                       stringsAsFactors = FALSE
                       )
head(shoes6, 50)
```


```{r}
namez4b
```


```{r}
nama4b2 <- names4b[[2]]
namez4b2 <- nama4b2[!grepl("Amazon Customer", nama4b2, ignore.case = TRUE)]
namez4b2 <- unique(namez4b2)
namez4b2 <- namez4b2[-(2:2)]
producto4b2 <- productnumber4b[[2]]
producto4b2 <- rep(producto4b2, length.out = length(namez4b2))
produc4b2 <- nameofproduct4b[[2]]
produc4b2 <- rep(produc4b2, length.out = length(namez4b2))
cater4b2 <- category4b[[4]]
ca4b2 <- rep(cater4b2, length.out = length(namez4b2))

ratingz4b2 <- ratings4b[[2]]
    if (length(ratingz4b2) > length(namez4b2)) {
    ratingz4b2 <- tail(ratingz4b2, length(namez4b2)) 
    } else if (length(ratingz4b2) < length(namez4b2)) {
    ratingz4b2 <- c(ratingz4b2, rep(NA, length(namez4b2) - length(ratingz4b2)))
    }
```


```{r}
shoes7 <- data.frame(Category = ca4b2,
                     Product_number = producto4b2,
                      Name_of_Product = produc4b2,
                      Userame = namez4b2,
                       Rating = ratingz4b2,
                       Date = dates4b[[2]],
                       Title_of_Review = title4b[[2]],
                       Text_of_Review = text4b[[2]],
                       stringsAsFactors = FALSE
                       )
head(shoes7, 50)
```


```{r}
namez4b2
```


```{r}
nama4b3 <- names4b[[3]]
namez4b3 <- nama4b3[!grepl("Men's comfort wide sneakers from FitVille", nama4b3, ignore.case = TRUE)]
namez4b3 <- namez4b3[-(1:2)]
namez4b3 <- unique(namez4b3)
producto4b3 <- productnumber4b[[3]]
producto4b3 <- rep(producto4b3, length.out = length(namez4b3))
produc4b3 <- nameofproduct4b[[3]]
produc4b3 <- rep(produc4b3, length.out = length(namez4b3))
cater4b3 <- category4b[[4]]
ca4b3 <- rep(cater4b3, length.out = length(namez4b3))

ratingz4b3 <- ratings4b[[3]]
    if (length(ratingz4b3) > length(namez4b3)) {
    ratingz4b3 <- tail(ratingz4b3, length(namez4b3)) 
    } else if (length(ratingz4b3) < length(namez4b3)) {
    ratingz4b3 <- c(ratingz4b3, rep(NA, length(namez4b3) - length(ratingz4b3)))
    }
```


```{r}
shoes8 <- data.frame(Category = ca4b3,
                     Product_number = producto4b3,
                      Name_of_Product = produc4b3,
                      Userame = namez4b3,
                       Rating = ratingz4b3,
                       Date = dates4b[[3]],
                       Title_of_Review = title4b[[3]],
                       Text_of_Review = text4b[[3]],
                       stringsAsFactors = FALSE
                       )
head(shoes8, 50)
```

```{r}
names4b[[3]]
```
 
```{r}
nama4b4 <- names4b[[4]]
namez4b4 <- nama4b4[!grepl("IGxx Fashion Glitter Men Women Pink Sequin Sneakers", nama4b4, ignore.case = TRUE)]
namez4b4 <- namez4b4[-(1:2)]
namez4b4 <- unique(namez4b4)
producto4b4 <- productnumber4b[[4]]
producto4b4 <- rep(producto4b4, length.out = length(namez4b4))
produc4b4 <- nameofproduct4b[[4]]
produc4b4 <- rep(produc4b4, length.out = length(namez4b4))
cater4b4 <- category4b[[4]]
ca4b4 <- rep(cater4b4, length.out = length(namez4b4))

ratingz4b4 <- ratings4b[[4]]
    if (length(ratingz4b4) > length(namez4b4)) {
    ratingz4b4 <- tail(ratingz4b4, length(namez4b4)) 
    } else if (length(ratingz4b4) < length(namez4b4)) {
    ratingz4b4 <- c(ratingz4b4, rep(NA, length(namez4b4) - length(ratingz4b4)))
    }
```


```{r}
shoes9 <- data.frame(Category = ca4b4,
                     Product_number = producto4b4,
                      Name_of_Product = produc4b4,
                      Userame = namez4b4,
                       Rating = ratingz4b4,
                       Date = dates4b[[4]],
                       Title_of_Review = title4b[[4]],
                       Text_of_Review = text4b[[4]],
                       stringsAsFactors = FALSE
                       )
head(shoes9, 50)
```

```{r}
names4b[[4]]
```



```{r}
nama4b5 <- names4b[[5]]
namez4b5 <- nama4b5[!grepl("Niluber Fashion Star Sneakers", nama4b5, ignore.case = TRUE)]
namez4b5 <- namez4b5[-(1:2)]
namez4b5 <- unique(namez4b5)
producto4b5 <- productnumber4b[[5]]
producto4b5 <- rep(producto4b5, length.out = length(namez4b5))
produc4b5 <- nameofproduct4b[[5]]
produc4b5 <- rep(produc4b5, length.out = length(namez4b5))
cater4b5 <- category4b[[4]]
ca4b5 <- rep(cater4b5, length.out = length(namez4b5))

ratingz4b5 <- ratings4b[[5]]
    if (length(ratingz4b5) > length(namez4b5)) {
    ratingz4b5 <- tail(ratingz4b5, length(namez4b5)) 
    } else if (length(ratingz4b5) < length(namez4b5)) {
    ratingz4b5 <- c(ratingz4b5, rep(NA, length(namez4b5) - length(ratingz4b5)))
    }
```


```{r}
shoes10 <- data.frame(Category = ca4b5,
                     Product_number = producto4b5,
                      Name_of_Product = produc4b5,
                      Userame = namez4b5,
                       Rating = ratingz4b5,
                       Date = dates4b[[5]],
                       Title_of_Review = title4b[[5]],
                       Text_of_Review = text4b[[5]],
                       stringsAsFactors = FALSE
                       )
head(shoes10, 50)
```

```{r}
names4b[[5]]
```
 

```{r}
urls5 <- c('https://www.amazon.com/dp/B0C7BK7FX6/ref=sspa_dk_detail_2?pd_rd_i=B0C7BK7FX6&pd_rd_w=vhdPf&content-id=amzn1.sym.be5cdf6a-f23a-4168-8100-e5595659876c&pf_rd_p=be5cdf6a-f23a-4168-8100-e5595659876c&pf_rd_r=5D6ZCXCW7744Q4VBDN63&pd_rd_wg=sNCOx&pd_rd_r=1d7a9030-87be-421e-9c87-091cd3a026c5&s=apparel&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&th=1&psc=1', 'https://www.amazon.com/dp/B074KL8RVS/ref=sspa_dk_detail_1?pd_rd_i=B074KL8RVS&pd_rd_w=j3s0F&content-id=amzn1.sym.f2f1cf8f-cab4-44dc-82ba-0ca811fb90cc&pf_rd_p=f2f1cf8f-cab4-44dc-82ba-0ca811fb90cc&pf_rd_r=K9M2D2W37NG5XG6AP4EM&pd_rd_wg=SGQx2&pd_rd_r=935bd5a9-bc65-43d0-8824-c7c80e74c966&s=apparel&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&th=1&psc=1','https://www.amazon.com/dp/B08F3HJL2W/ref=sspa_dk_detail_0?psc=1&pd_rd_i=B08F3HJL2W&pd_rd_w=UAkma&content-id=amzn1.sym.10c716f0-b18a-473a-9d6a-5d87bc47ef1e&pf_rd_p=10c716f0-b18a-473a-9d6a-5d87bc47ef1e&pf_rd_r=G6723859P14MZYAX66GK&pd_rd_wg=78AZX&pd_rd_r=dd950c98-8023-4103-a8c6-022b0ed35cd1&s=apparel&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM','https://www.amazon.com/dp/B07QRZBPGV/ref=sspa_dk_detail_0?psc=1&pd_rd_i=B07QRZBPGV&pd_rd_w=cvp6B&content-id=amzn1.sym.10c716f0-b18a-473a-9d6a-5d87bc47ef1e&pf_rd_p=10c716f0-b18a-473a-9d6a-5d87bc47ef1e&pf_rd_r=4VK2P5P59VYSHX14SNJD&pd_rd_wg=fwLso&pd_rd_r=8b95485b-060b-4185-9328-6ec8322dfe6e&s=apparel&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM','https://www.amazon.com/dp/B01LI4IDO6/ref=sspa_dk_detail_2?pd_rd_i=B01LI4IDO6&pd_rd_w=w4xwJ&content-id=amzn1.sym.f2f1cf8f-cab4-44dc-82ba-0ca811fb90cc&pf_rd_p=f2f1cf8f-cab4-44dc-82ba-0ca811fb90cc&pf_rd_r=REQKN8FJBNNZ41T5XMH2&pd_rd_wg=xFIjN&pd_rd_r=a2189ca8-6109-4e75-b6b6-7e78d50d2063&s=apparel&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM&th=1&psc=1')

nameofproduct5 <-vector("list", length(urls5))
names5 <- vector("list", length(urls5))
ratings5 <- vector("list", length(urls5))
dates5 <- vector("list", length(urls5))
title5 <- vector("list", length(urls5))
text5 <- vector("list", length(urls5))
n5 <- vector("list", length(urls5))
```

```{r}
df <- list()
for (i in seq_along(urls5)) {
    session <- bow(urls5[i], user_agent = "Educational")
  webpage5 <- scrape(session)
  nam5 <-webpage5 %>% html_nodes(".a-profile-name") %>% html_text()
  nam5 <- nam5[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam5, ignore.case = TRUE)]
    nam5 <- nam5[nam5 != ""]
    n5[[i]] <- nam5
    name5 <- c() 
    non_amazon_seen5 <- FALSE  
    for (na5 in nam5) {
      if (na5 == "Amazon Customer") {
        if (non_amazon_seen5) {
          name5 <- c(name5, na5)
        }
      } else {
        name5 <- c(name5, na5)
        non_amazon_seen5 <- TRUE
        }
    }
    name5 <- name5[!duplicated(name5) | name5 == "Amazon Customer"]
    names5[[i]] <- name5
    
        nameofproduct5[[i]] <-  webpage5 %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct5[[i]] <- rep(nameofproduct5[[i]], length.out = length(names5[[i]]))
    
    rate5 <- webpage5 %>% html_nodes(".a-icon-alt") %>% html_text()
    rati5 <- rate5[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate5, ignore.case = TRUE)]
    rat5 <- gsub(" out of 5 stars", "", rati5)
    rats5 <- rat5
    if (length(rats5) > length(name5)) {
    rats5 <- tail(rats5, length(name5)) 
    } else if (length(rats5) < length(name5)) {
    rats5 <- c(rats5, rep(NA, length(name5) - length(rats5)))
    }
    ratings5[[i]] <- rats5
    
    dat5 <- webpage5 %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date5 <- gsub("Reviewed.*on ", "", dat5)
    dates5[[i]] <- date5
    titl5 <- webpage5 %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit5 <- gsub("Reviewed.*on ", "", titl5)
    ti5 <- gsub(".*stars\\s*", "", tit5)
    t5 <- gsub("\\s+", " ", ti5)
    title5[[i]] <- t5
    tex5 <- webpage5 %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te5 <- gsub("\\n", " ", tex5)
    t5 <- gsub("\\s+", " ", te5)
    text5[[i]] <- trimws(t5)
}
```

```{r}
cate5 <- c("Category 1: WATCH", "Category 2", "Category 3", "Category 4: SHOES", "Category 5: PANTS")
category5 <- vector("list", length(cate5))
for (i in seq_along(cate5)) {
    category5[[i]] <- cate5[i]
}
```

```{r}
for (i in seq_along(urls5)) {
    category5[[i]] <- rep(category5[[i]], length.out = length(names5[[i]]))
}
```

```{r}
productnumbe5 <- c("Product 1", "Product 2", "Product 3", "Product 4", "Product 5")
productnumber5 <- vector("list", length(productnumbe5))
for (i in seq_along(productnumbe5)) {
    productnumber5[[i]] <- productnumbe5[i]
}
for (i in seq_along(urls5)) {
    productnumber5[[i]] <- rep(productnumber5[[i]], length.out = length(names5[[i]]))
}
```

```{r}
nama5 <- names5[[1]]
namez5 <- nama5[!grepl("Lee Women's Ultra Lux Comfort with Flex Motion Bootcut Jean", nama5, ignore.case = TRUE)]
namez5 <- unique(namez5)
namez5 <- namez5[-1]
producto5 <- productnumber5[[1]]
producto5 <- rep(producto5, length.out = length(namez5))
produc5 <- nameofproduct5[[1]]
produc5 <- rep(produc5, length.out = length(namez5))
cater5 <- category5[[5]]
ca5 <- rep(cater5, length.out = length(namez5))
ratingz5 <- ratings5[[1]]
    if (length(ratingz5) > length(namez5)) {
    ratingz5 <- tail(ratingz5, length(namez5)) 
    } else if (length(ratingz5) < length(namez5)) {
    ratingz5 <- c(ratingz5, rep(NA, length(namez5) - length(ratingz5)))
    }
```

```{r}
pants1 <- data.frame(Category = ca5,
                     Product_number = producto5,
                      Name_of_Product = produc5,
                      Userame = namez5,
                       Rating = ratingz5,
                       Date = dates5[[1]],
                       Title_of_Review = title5[[1]],
                       Text_of_Review = text5[[1]],
                       stringsAsFactors = FALSE
                       )
head(pants1, 50)
```

```{r}
names5[[1]]
```


```{r}
nama52 <- names5[[2]]
namez52 <- nama52[!grepl("carlton johnson", nama52, ignore.case = TRUE)]
namez52 <- unique(namez52)
namez52 <- namez52[-(2:2)]
producto52 <- productnumber5[[2]]
producto52 <- rep(producto52, length.out = length(namez52))
produc52 <- nameofproduct5[[2]]
produc52 <- rep(produc52, length.out = length(namez52))
cater52 <- category5[[5]]
ca52 <- rep(cater52, length.out = length(namez52))

ratingz52 <- ratings5[[2]]
    if (length(ratingz52) > length(namez52)) {
    ratingz52 <- tail(ratingz52, length(namez52)) 
    } else if (length(ratingz52) < length(namez52)) {
    ratingz52 <- c(ratingz52, rep(NA, length(namez52) - length(ratingz52)))
    }
```


```{r}
pants2 <- data.frame(Category = ca52,
                     Product_number = producto52,
                      Name_of_Product = produc52,
                      Userame = namez52,
                       Rating = ratingz52,
                       Date = dates5[[2]],
                       Title_of_Review = title5[[2]],
                       Text_of_Review = text5[[2]],
                       stringsAsFactors = FALSE
                       )
head(pants2, 50)
```


```{r}
names5[[2]]
```

```{r}
nama53 <- names5[[3]]
namez53 <- nama53[!grepl("Mens Lightweight Gym Jogger Pants,Men's Workout Sweatpants", nama53, ignore.case = TRUE)]
namez53 <- unique(namez53)
namez53 <- namez53[-(2:2)]
producto53 <- productnumber5[[3]]
producto53 <- rep(producto53, length.out = length(namez53))
produc53 <- nameofproduct5[[3]]
produc53 <- rep(produc53, length.out = length(namez52))
cater53 <- category5[[5]]
ca53 <- rep(cater53, length.out = length(namez52))

ratingz53 <- ratings5[[3]]
    if (length(ratingz53) > length(namez53)) {
    ratingz53 <- tail(ratingz53, length(namez53)) 
    } else if (length(ratingz53) < length(namez53)) {
    ratingz53 <- c(ratingz53, rep(NA, length(namez53) - length(ratingz53)))
    }
```


```{r}
pants3 <- data.frame(Category = ca53,
                     Product_number = producto53,
                      Name_of_Product = produc53,
                      Userame = namez53,
                       Rating = ratingz53,
                       Date = dates5[[3]],
                       Title_of_Review = title5[[3]],
                       Text_of_Review = text5[[3]],
                       stringsAsFactors = FALSE
                       )
head(pants3, 50)
```

```{r}
names5[[3]]
```

```{r}
nama54 <- names5[[4]]
namez54 <- nama54[!grepl("BROKIG Mens Zip Joggers Pants - Casual Gym Workout Track Pants Comfortable Slim Fit Tapered Sweatpants with Pockets", nama54, ignore.case = TRUE)]
namez54 <- namez54[-(1:2)]
namez54 <- unique(namez54)
producto54 <- productnumber5[[4]]
producto54 <- rep(producto54, length.out = length(namez54))
produc54 <- nameofproduct5[[4]]
produc54 <- rep(produc54, length.out = length(namez54))
cater54 <- category5[[4]]
ca54 <- rep(cater54, length.out = length(namez54))
ratingz54 <- ratings5[[4]]
    if (length(ratingz54) > length(namez54)) {
    ratingz54 <- tail(ratingz54, length(namez54)) 
    } else if (length(ratingz54) < length(namez54)) {
    ratingz54 <- c(ratingz54, rep(NA, length(namez54) - length(ratingz54)))
    }
```

```{r}
pants4 <- data.frame(Category = ca54,
                     Product_number = producto54,
                      Name_of_Product = produc54,
                      Userame = namez54,
                       Rating = ratingz54,
                       Date = dates5[[4]],
                       Title_of_Review = title5[[4]],
                       Text_of_Review = text5[[4]],
                       stringsAsFactors = FALSE
                       )
head(pants4, 50)
```

```{r}
names5[[4]]
```

```{r}
nama55 <- names5[[5]]
namez55 <- nama55[!grepl("Lee Men's Extreme Motion Straight Taper Jean", nama55, ignore.case = TRUE)]
namez55 <- namez55[-(1:2)]
namez55 <- unique(namez55)
producto55 <- productnumber5[[5]]
producto55 <- rep(producto55, length.out = length(namez55))
produc55 <- nameofproduct5[[5]]
produc55 <- rep(produc55, length.out = length(namez55))
cater55 <- category5[[5]]
ca55 <- rep(cater55, length.out = length(namez55))
ratingz55 <- ratings5[[5]]
    if (length(ratingz55) > length(namez55)) {
    ratingz55 <- tail(ratingz55, length(namez55)) 
    } else if (length(ratingz55) < length(namez55)) {
    ratingz55 <- c(ratingz55, rep(NA, length(namez55) - length(ratingz55)))
    }
```

```{r}
pants5 <- data.frame(Category = ca55,
                     Product_number = producto55,
                      Name_of_Product = produc55,
                      Userame = namez55,
                       Rating = ratingz55,
                       Date = dates5[[5]],
                       Title_of_Review = title5[[5]],
                       Text_of_Review = text5[[5]],
                       stringsAsFactors = FALSE
                       )
head(pants5, 50)
```
```{r}
names5[[5]]
```

```{r}
urls5b <- c('https://www.amazon.com/Wrangler-Authentics-Relaxed-Stretch-Cargo/dp/B0BTRMKQW5/ref=sr_1_6?dib=eyJ2IjoiMSJ9.lxTaNXjcDhEwKCXa5-a-BQEAx7Lju222fMupvQJu2rVIXc909ErUfmNRjUtKWzP_liVuPYd9ZRcKbBizYMJ9xTAGoKM_RP7260aLRx2IbrHJwRLl01ZA-3t0FWWaef07BftP5QoyZvRqGOsi6Z7ZSnKbzBtBT-beIhZ0EfQ8h1Bpv4ZHvE9to24bec4rvvCBC01G_aO__RoJEFT2Sx0zJmfCz9deWM7USLlAd68ygH0-mmh6MgukZAeirtNO3n2hyDtmVSAROzbn7YuR9zofaOfKPAxOOIr5xLIQ8nFC_sg.ZfOVK2JcrdlQPqGEXjljkpeiZ7nKtWsxODiaQGJUFNs&dib_tag=se&keywords=pants&qid=1733793880&sr=8-6', 'https://www.amazon.com/roswear-Womens-Casual-Waisted-Stretch/dp/B0CFV5LFH5/ref=sr_1_7?crid=3VHC0LVWREKOJ&dib=eyJ2IjoiMSJ9.UOx5KTDqeefUG2TUYs--4M3IdXBkdZGU7Uw4AqWMYfRaN_P7tfR-jIF2xPFxTRK5Qpw222M1MJzv6-PrvmPcTwyw1RYUV6HQaN1zO6XEQsV0YeGQaIsZiZnX2nnNqKnLBL4RgQ8z1CEpGoO5nctbA6c2A0rkbOO41B2Gif7OxWeW_U6pmJufC_exjdujFInhvP8fGfP4QGtEIa8HsHQeS4ItW2b1-5G2GtZSuZ2ShIMoicNsEIYsgYmAZhpxq_EXiuqTNbbV5jJcS6gn_ouTChVu9ztU_0aUwRbmsVKISX4pFb1auVZYqY_da9mHNVvzJfMq0c-4kDnBOjGGDGRW5VfKRnPGSW849VqHkUp6yxeReN3ts59Dm0fxBemIyR4xAcZ7jyu7eax01QU9vz5Sjdz5jn8RxH-WUTKbmSmpXSsJ4xFTWOzrnzBrcTblcv2d.F3tqRjp4re4adLh7GofLfucFrDDnvOll8xxEe4vN36o&dib_tag=se&keywords=jeans%2Bfor%2Bwomen%2Bhigh%2Bwaist&qid=1734176788&sprefix=jeans%2Caps%2C639&sr=8-7&th=1', 'https://www.amazon.com/Dickies-Relaxed-Carpenter-Brown-38x30/dp/B000N8Q4L8/ref=sr_1_45?crid=37RW59WJQBXIZ&dib=eyJ2IjoiMSJ9.i5rbca9TP-x-QL-RAnbbduGa-WYcKxCMbcTN_1pNzzpkrwbV6_h92jfTY0kfDn89_XBHzxQOxjAJBWZT-2MPSQu-6fu6w-ruDHOGNH8ue_IdOv--tW9dpbxwGXTG8Lvz_u7RYEgLY4biGH4V8MjYpHlOHEvpZEP_S1rVqfShtor3GDcdNSoxAv4tV9m4Iq7FLg_Ob2uRb8b6YKbG-kllbzLq6mXDb9nc2HbNWs1jU9u0-1vlBwHgQlb7pQpImHOI-EZbjaZ2DXe_higkkr6ul4vysdCRS_PHRYNFUm9K3fdiuQnICksp07a2ozQ4Tsz6SXAM0LTWlMJaBYBaXgXq1jsmMJR0HHnfihmPwdVyOqqD7wKADICWizpuKByvpQBgZyMhcU6Cp2I4JzD7hTnsiaxYmH2pz-_KEDt9TiEHa0YE1FXtbM032TOsGgjTZxxF.dOrMOZYbdsYWcl0jffffp_ECF7ZrhSt32ZlrbNT-l6Q&dib_tag=se&keywords=jeans&qid=1734177723&sprefix=jea%2Caps%2C625&sr=8-45&th=1', 'https://www.amazon.com/Amazon-Essentials-Slim-Fit-Stretch-Black/dp/B07BJLD57Q/ref=sr_1_1_ffob_sspa?crid=2OWP7XAQU2G8B&dib=eyJ2IjoiMSJ9.i5rbca9TP-x-QL-RAnbbduGa-WYcKxCMbcTN_1pNzzpkrwbV6_h92jfTY0kfDn89_XBHzxQOxjAJBWZT-2MPSQu-6fu6w-ruDHOGNH8ue_IdOv--tW9dpbxwGXTG8Lvz_u7RYEgLY4biGH4V8MjYpHlOHEvpZEP_S1rVqfShtor3GDcdNSoxAv4tV9m4Iq7FLg_Ob2uRb8b6YKbG-kllbzLq6mXDb9nc2HbNWs1jU9u0-1vlBwHgQlb7pQpImHOI-EZbjaZ2DXe_higkkr6ul2yPV6KmTkvlP6Pd46lqnS8.P6l1p8y7Preos6aUv8e4CVZg3FeAPWkEEgGt3zxlPzM&dib_tag=se&keywords=jeans&qid=1734179449&sprefix=jeans%2Caps%2C489&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&psc=1', 'https://www.amazon.com/Childrens-Place-Girls-Bootcut-Denim/dp/B0861XZ6JP/ref=sr_1_3_sspa?crid=1HZTTXUBY4FID&dib=eyJ2IjoiMSJ9.1-myxxT2UVtDbGeWB7hGkvvtlEkJa85TMj4ivlkYotBRIvEq21BEGZ5ooNHlaXKnxNLZ-z8zeUhUqXMAxlFa1lpKt7BJGWNoZi2-pDrfoVJ1IyEmeiJwlBa4UzbgmirQKvC7NZFSjMyvHLbCGzWgngipic-al_6NfeGfACuvoOr0KtVRt6NMCtVvGNkat8seOAdo-I324tl8LuTlUM11s2QyzeJeiZornUA8gmeiZqMwPbjKnGxTt35gBAE0AhvS8wDi4ux6tdtosw1mvQWV6Ofa-j5M0MnB81FvdHPyjwU.TAPd-aZe373sAyp1YmaRaNIaN4xgO4UxfeRFHgZWoUw&dib_tag=se&keywords=jeans%2Bkids&qid=1734178120&sprefix=jeans%2Bkid%2Caps%2C528&sr=8-3-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&psc=1')

nameofproduct5b <-vector("list", length(urls5b))
names5b <- vector("list", length(urls5b))
ratings5b <- vector("list", length(urls5b))
dates5b <- vector("list", length(urls5b))
title5b <- vector("list", length(urls5b))
text5b <- vector("list", length(urls5b))
n5b <- vector("list", length(urls5b))
```


```{r}
df <- list()

for (i in seq_along(urls5b)) {
    session <- bow(urls5b[i], user_agent = "Educational")

  webpage5b <- scrape(session)

  nam5b <-webpage5b %>% html_nodes(".a-profile-name") %>% html_text()
  nam5b <- nam5b[!grepl("Fitbit Charge 6|AEAC Smart Watch", nam5b, ignore.case = TRUE)]
    nam5b <- nam5b[nam5b != ""]
    n5b[[i]] <- nam5b
    name5b <- c() 
    non_amazon_seen5b <- FALSE  
    for (na5b in nam5b) {
      if (na5b == "Amazon Customer") {

        if (non_amazon_seen5b) {
          name5b <- c(name5b, na5b)
        }
      } else {
        name5b <- c(name5b, na5b)
        non_amazon_seen5b <- TRUE
        }
    }
    name5b <- name5b[!duplicated(name5b) | name5b == "Amazon Customer"]
    names5b[[i]] <- name5b
    
        nameofproduct5b[[i]] <-  webpage5b %>%
  html_nodes('.a-size-large.product-title-word-break') %>%
  html_text()
    nameofproduct5b[[i]] <- rep(nameofproduct5b[[i]], length.out = length(names5b[[i]]))
    
    rate5b <- webpage5b %>% html_nodes(".a-icon-alt") %>% html_text()
    rati5b <- rate5b[!grepl("Previous page|Next page|Previous set of slides|Next set of slides", rate5b, ignore.case = TRUE)]
    rat5b <- gsub(" out of 5 stars", "", rati5b)
    rats5b <- rat5b
    if (length(rats5b) > length(name5b)) {
    rats5b <- tail(rats5b, length(name5b)) 
    } else if (length(rats5b) < length(name5b)) {
    rats5b <- c(rats5b, rep(NA, length(name5b) - length(rats5b)))
    }

    ratings5b[[i]] <- rats5b
    
    dat5b <- webpage5b %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date5b <- gsub("Reviewed.*on ", "", dat5b)
    dates5b[[i]] <- date5b

    titl5b <- webpage5b %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    tit5b <- gsub("Reviewed.*on ", "", titl5b)
    ti5b <- gsub(".*stars\\s*", "", tit5b)
    t5b <- gsub("\\s+", " ", ti5b)
    title5b[[i]] <- t5b

    tex5b <- webpage5b %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    te5b <- gsub("\\n", " ", tex5b)
    t5b <- gsub("\\s+", " ", te5b)
    text5b[[i]] <- trimws(t5b)
}
```


```{r}
cate5b <- c("Category 1: WATCH", "Category 2", "Category 3", "Category 4: SHOES", "Category 5: PANTS")
category5b <- vector("list", length(cate5b))
for (i in seq_along(cate5b)) {
    category5b[[i]] <- cate5b[i]
}
```


```{r}
for (i in seq_along(urls5b)) {
    category5b[[i]] <- rep(category5b[[i]], length.out = length(names5b[[i]]))
}
```


```{r}
productnumbe5b <- c("Product 6", "Product 7", "Product 8", "Product 9", "Product 10")
productnumber5b <- vector("list", length(productnumbe5b))
for (i in seq_along(productnumbe5b)) {
    productnumber5b[[i]] <- productnumbe5b[i]
}
for (i in seq_along(urls5b)) {
    productnumber5b[[i]] <- rep(productnumber5b[[i]], length.out = length(names5b[[i]]))
}
```


```{r}
nama5b <- names5b[[1]]
namez5b <- nama5b[!grepl("AmazingNobody", nama5b, ignore.case = TRUE)]
namez5b <- unique(namez5b)
namez5b <- namez5b[-1]
producto5b <- productnumber5b[[1]]
producto5b <- rep(producto5b, length.out = length(namez5b))
produc5b <- nameofproduct5b[[1]]
produc5b <- rep(produc5b, length.out = length(namez5b))
cater5b <- category5b[[5]]
ca5b <- rep(cater5b, length.out = length(namez5b))

ratingz5b <- ratings5b[[1]]
    if (length(ratingz5b) > length(namez5b)) {
    ratingz5b <- tail(ratingz5b, length(namez5b)) 
    } else if (length(ratingz5b) < length(namez5b)) {
    ratingz5b <- c(ratingz5b, rep(NA, length(namez5b) - length(ratingz5b)))
    }
```


```{r}
pants6 <- data.frame(Category = ca5b,
                     Product_number = producto5b,
                      Name_of_Product = produc5b,
                      Userame = namez5b,
                       Rating = ratingz5b,
                       Date = dates5b[[1]],
                       Title_of_Review = title5b[[1]],
                       Text_of_Review = text5b[[1]],
                       stringsAsFactors = FALSE
                       )
head(pants6, 50)
```

```{r}
namez5b
```


```{r}
nama5b2 <- names5b[[2]]
namez5b2 <- nama5b2[!grepl("Amazon Customer", nama5b2, ignore.case = TRUE)]
namez5b2 <- unique(namez5b2)
namez5b2 <- namez5b2[-(2:2)]
producto5b2 <- productnumber5b[[2]]
producto5b2 <- rep(producto5b2, length.out = length(namez5b2))
produc5b2 <- nameofproduct5b[[2]]
produc5b2 <- rep(produc5b2, length.out = length(namez5b2))
cater5b2 <- category5b[[5]]
ca5b2 <- rep(cater5b2, length.out = length(namez5b2))

ratingz5b2 <- ratings5b[[2]]
    if (length(ratingz5b2) > length(namez5b2)) {
    ratingz5b2 <- tail(ratingz5b2, length(namez5b2)) 
    } else if (length(ratingz5b2) < length(namez5b2)) {
    ratingz5b2 <- c(ratingz5b2, rep(NA, length(namez5b2) - length(ratingz5b2)))
    }
```


```{r}
pants7 <- data.frame(Category = ca5b2,
                     Product_number = producto5b2,
                      Name_of_Product = produc5b2,
                      Userame = namez5b2,
                       Rating = ratingz5b2,
                       Date = dates5b[[2]],
                       Title_of_Review = title5b[[2]],
                       Text_of_Review = text5b[[2]],
                       stringsAsFactors = FALSE
                       )
head(pants7, 50)
```

```{r}
names5b[[2]]
```

```{r}
nama5b3 <- names5b[[3]]
namez5b3 <- nama5b3[!grepl("Dickies Men's Big-Tall Relaxed Fit Jean", nama5b3, ignore.case = TRUE)]
namez5b3 <- unique(namez5b3)
namez5b3 <- namez5b3[-(2:2)]
producto5b3 <- productnumber5b[[3]]
producto5b3 <- rep(producto5b3, length.out = length(namez5b3))
produc5b3 <- nameofproduct5b[[3]]
produc5b3 <- rep(produc5b3, length.out = length(namez5b3))
cater5b3 <- category5b[[5]]
ca5b3 <- rep(cater5b3, length.out = length(namez5b3))

ratingz5b3 <- ratings5b[[3]]
    if (length(ratingz5b3) > length(namez5b3)) {
    ratingz5b3 <- tail(ratingz5b3, length(namez5b3)) 
    } else if (length(ratingz5b3) < length(namez5b3)) {
    ratingz5b3 <- c(ratingz5b3, rep(NA, length(namez5b3) - length(ratingz5b3)))
    }
```


```{r}
pants8 <- data.frame(Category = ca5b3,
                     Product_number = producto5b3,
                      Name_of_Product = produc5b3,
                      Userame = namez5b3,
                       Rating = ratingz5b3,
                       Date = dates5b[[3]],
                       Title_of_Review = title5b[[3]],
                       Text_of_Review = text5b[[3]],
                       stringsAsFactors = FALSE
                       )
head(pants8, 50)
```

```{r}
names5b[[3]]
```

```{r}
nama5b4 <- names5b[[4]]
namez5b4 <- nama5b4[!grepl("Crystal *The Champagne Bubbly*", nama5b4, ignore.case = TRUE)]
namez5b4 <- unique(namez5b4)
namez5b4 <- namez5b4[-(2:2)]
producto5b4 <- productnumber5b[[4]]
producto5b4 <- rep(producto5b4, length.out = length(namez5b4))
produc5b4 <- nameofproduct5b[[4]]
produc5b4 <- rep(produc5b4, length.out = length(namez5b4))
cater5b4 <- category5b[[5]]
ca5b4 <- rep(cater5b4, length.out = length(namez5b4))

ratingz5b4 <- ratings5b[[4]]
    if (length(ratingz5b4) > length(namez5b4)) {
    ratingz5b4 <- tail(ratingz5b4, length(namez5b4)) 
    } else if (length(ratingz5b4) < length(namez5b4)) {
    ratingz5b4 <- c(ratingz5b4, rep(NA, length(namez5b4) - length(ratingz5b4)))
    }
```


```{r}
pants9 <- data.frame(Category = ca5b4,
                     Product_number = producto5b4,
                      Name_of_Product = produc5b4,
                      Userame = namez5b4,
                       Rating = ratingz5b4,
                       Date = dates5b[[4]],
                       Title_of_Review = title5b[[4]],
                       Text_of_Review = text5b[[4]],
                       stringsAsFactors = FALSE
                       )
head(pants9, 50)
```

```{r}
names5b[[4]]
```

 
```{r}
nama5b5 <- names5b[[5]]
namez5b5 <- nama5b5[!grepl("fun mama 0912", nama5b5, ignore.case = TRUE)]
namez5b5 <- unique(namez5b5)
namez5b5 <- namez5b5[-(2:2)]
producto5b5 <- productnumber5b[[5]]
producto5b5 <- rep(producto5b5, length.out = length(namez5b5))
produc5b5 <- nameofproduct5b[[5]]
produc5b5 <- rep(produc5b5, length.out = length(namez5b5))
cater5b5 <- category5b[[5]]
ca5b5 <- rep(cater5b5, length.out = length(namez5b5))

ratingz5b5 <- ratings5b[[5]]
    if (length(ratingz5b5) > length(namez5b5)) {
    ratingz5b5 <- tail(ratingz5b5, length(namez5b5)) 
    } else if (length(ratingz5b5) < length(namez5b5)) {
    ratingz5b5 <- c(ratingz5b5, rep(NA, length(namez5b5) - length(ratingz5b5)))
    }
```


```{r}
pants10 <- data.frame(Category = ca5b5,
                     Product_number = producto5b5,
                      Name_of_Product = produc5b5,
                      Userame = namez5b5,
                       Rating = ratingz5b5,
                       Date = dates5b[[5]],
                       Title_of_Review = title5b[[5]],
                       Text_of_Review = text5b[[5]],
                       stringsAsFactors = FALSE
                       )
head(pants10, 50)
```
```{r}
names5b[[5]]
```
 
