---
title: "RWorksheet#5_group.Rmd"
author: "Baylon_Calvario_Calzado"
date: "2024-11-01"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(polite)
library(kableExtra)
library(rmarkdown)
library(httr)
library(rvest)
library(dplyr)
library(stringr)
```

```{r}
urls <- c('https://www.amazon.com/s?k=skin+care&crid=3FODLJK4URUE9&sprefix=skin%2Caps%2C510&ref=nb_sb_ss_ts-doa-p_1_4', 'https://www.amazon.com/s?k=perfume&crid=1MRC8YEDNO62V&sprefix=perfume%2Caps%2C397&ref=nb_sb_noss_1', 'https://www.amazon.com/s?k=bags+for+women&ref=nb_sb_noss', 'https://www.amazon.com/s?k=shoes&crid=QOEP1YQOC5W&sprefix=shoe%2Caps%2C1302&ref=nb_sb_noss_2', 'https://www.amazon.com/s?k=pants&ref=nb_sb_noss')

nameofproduct <- vector("list", length(urls))
price <- vector("list", length(urls))
description <- vector("list", length(urls))
Ratings <- vector("list", length(urls))
Reviews <- vector("list", length(urls))
```


```{r}
df <- list()

for (i in seq_along(urls)) {
    session <- bow(urls[i], user_agent = "Educational")
    webpage <- scrape(session)

nameofproduct[[i]] <-  webpage %>%
  html_nodes('.a-size-base-plus.a-color-base') %>%
  html_text() %>%
  head(30)

price[[i]] <-  webpage %>%
  html_nodes('.a-price-whole') %>%
  html_text() %>%
  head(30)

description[[i]] <-  webpage %>%
  html_nodes('.a-size-mini.a-spacing-none.a-color-base s-line-clamp-3') %>%
  html_text() %>%
  head(30)

Ratings[[i]] <-  webpage %>%
  html_nodes('.a-icon.a-icon-star-small.a-star-small-4-5') %>%
  html_text() %>%
  head(30)

Reviews[[i]] <-  webpage %>%
  html_nodes('.a-size-base-plus.a-color-base') %>%
  html_text() %>%
  head(30)
}
```


```{r}

skincare <- data.frame(nameofproduct[[1]],
                       Price = price[[1]],
                       Ratings = Ratings[[1]],
                       stringsAsFactors = FALSE
                       )
head(skincare)
```
```{r}
perfume <- data.frame(nameofproduct[[2]],
                       Price = price[[2]],
                       Ratings = Ratings[[2]],
                       stringsAsFactors = FALSE
                       )
head(perfume)
```
```{r}
bags <- data.frame(nameofproduct[[3]],
                       Price = price[[3]],
                       Ratings = Ratings[[3]],
                       stringsAsFactors = FALSE
                       )
head(bags)
```
```{r}
shoes <- data.frame(nameofproduct[[4]],
                       Price = price[[4]],
                       Ratings = Ratings[[4]],
                       stringsAsFactors = FALSE
                       )
head(shoes)
```
```{r}
pants <- data.frame(nameofproduct[[5]],
                       Price = price[[5]],
                       Ratings = Ratings[[5]],
                       stringsAsFactors = FALSE
                       )
head(pants)
```
#ffdgbfh
