---
title: "RWorksheet#5_group.Rmd"
author: "Baylon_Calvario_Calzado"
date: "2024-11-20"
output:
  pdf_document:
   latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(polite)
library(kableExtra)
library(rmarkdown)
library(httr)
library(rvest)
library(dplyr)
library(stringr)
library(ggplot2)
library(knitr)
```

```{r}
urls <- c('https://www.amazon.com/Fitbit-Exercise-Equipment-6-Months-Membership/dp/B0CC62ZG1M/?_encoding=UTF8&pd_rd_w=26Qi3&content-id=amzn1.sym.7f957896-9457-4ac3-8c2b-58f2b6be2857&pf_rd_p=7f957896-9457-4ac3-8c2b-58f2b6be2857&pf_rd_r=83Q7T410CX2F8JA6HGMP&pd_rd_wg=2KdNs&pd_rd_r=ceb495d9-920d-4e7a-b0da-edda53c0415a&ref_=pd_hp_d_btf_exports_top_sellers_unrec&th=1')

name <- vector("list", length(urls))
ratings <- vector("list", length(urls))
date <- vector("list", length(urls))
title <- vector("list", length(urls))
text <- vector("list", length(urls))
```

```{r}
df <- list()

for (i in seq_along(urls)) {
    session <- bow(urls[i], user_agent = "Educational")
    page <- scrape(session)
    
    nam <- page %>% html_nodes(".a-profile-name") %>% html_text()
    nam <- nam[!grepl("Fitbit Charge 6|Amazon Customer", nam, ignore.case = TRUE)]
    nam <- nam[nam != ""]
    name[[i]] <- unique(nam)

    rate <- page %>% html_nodes(".a-icon-alt") %>% html_text()
    rating <- rate[!grepl("Previous page|Next page", rate, ignore.case = TRUE)]
    rating <- gsub(" out of 5 stars", "", rating)
    rating <- rating[-(1:15)]
    ratings[[i]] <- rating[-c(3,7)]

    dat <- page %>% html_nodes(".a-size-base.a-color-secondary.review-date") %>% html_text()
    date[[i]] <- gsub("Reviewed.*on ", "", dat)

    titl <- page %>% html_nodes(".a-size-base.review-title.a-color-base.review-title-content.a-text-bold") %>% html_text()
    titl <- gsub("Reviewed.*on ", "", titl)
    titl <- gsub(".*stars\\s*", "", titl)
    title[[i]] <- gsub("\\s+", " ", titl)

    tex <- page %>% html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>% html_text()
    tex <- gsub("\\n", " ", tex)
    tex <- gsub("\\s+", " ", tex)
    text[[i]] <- trimws(tex)
}
```


```{r}
Watch1 <- data.frame(
    Name = unlist(name[1]),          
    Ratings = unlist(ratings[1]),    
    DateofReview = unlist(date[1]),  
    TitleofReview = unlist(title[1]),
    stringsAsFactors = FALSE)
head(Watch1)
Watch1 %>%
    kable("latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "scale_down")
```
```{r}
TextofReview1 <- text[1]
TextofReview1
```

